/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthChangePasswordRequest
 */
export interface AuthChangePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof AuthChangePasswordRequest
     */
    oldPassword: string;
    /**
     * 
     * @type {string}
     * @memberof AuthChangePasswordRequest
     */
    newPassword: string;
    /**
     * 
     * @type {number}
     * @memberof AuthChangePasswordRequest
     */
    userId: number;
}

/**
 * Check if a given object implements the AuthChangePasswordRequest interface.
 */
export function instanceOfAuthChangePasswordRequest(value: object): value is AuthChangePasswordRequest {
    if (!('oldPassword' in value) || value['oldPassword'] === undefined) return false;
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function AuthChangePasswordRequestFromJSON(json: any): AuthChangePasswordRequest {
    return AuthChangePasswordRequestFromJSONTyped(json, false);
}

export function AuthChangePasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthChangePasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'oldPassword': json['oldPassword'],
        'newPassword': json['newPassword'],
        'userId': json['userId'],
    };
}

export function AuthChangePasswordRequestToJSON(json: any): AuthChangePasswordRequest {
    return AuthChangePasswordRequestToJSONTyped(json, false);
}

export function AuthChangePasswordRequestToJSONTyped(value?: AuthChangePasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'oldPassword': value['oldPassword'],
        'newPassword': value['newPassword'],
        'userId': value['userId'],
    };
}

