/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckUsernameExists200Response
 */
export interface CheckUsernameExists200Response {
    /**
     * 
     * @type {boolean}
     * @memberof CheckUsernameExists200Response
     */
    _exists: boolean;
}

/**
 * Check if a given object implements the CheckUsernameExists200Response interface.
 */
export function instanceOfCheckUsernameExists200Response(value: object): value is CheckUsernameExists200Response {
    if (!('_exists' in value) || value['_exists'] === undefined) return false;
    return true;
}

export function CheckUsernameExists200ResponseFromJSON(json: any): CheckUsernameExists200Response {
    return CheckUsernameExists200ResponseFromJSONTyped(json, false);
}

export function CheckUsernameExists200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckUsernameExists200Response {
    if (json == null) {
        return json;
    }
    return {
        
        '_exists': json['exists'],
    };
}

export function CheckUsernameExists200ResponseToJSON(json: any): CheckUsernameExists200Response {
    return CheckUsernameExists200ResponseToJSONTyped(json, false);
}

export function CheckUsernameExists200ResponseToJSONTyped(value?: CheckUsernameExists200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'exists': value['_exists'],
    };
}

