/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PostponeTuitionFee } from './PostponeTuitionFee';
import {
    PostponeTuitionFeeFromJSON,
    PostponeTuitionFeeFromJSONTyped,
    PostponeTuitionFeeToJSON,
    PostponeTuitionFeeToJSONTyped,
} from './PostponeTuitionFee';

/**
 * 
 * @export
 * @interface CreatePostponeTuitionRequestPostRequest
 */
export interface CreatePostponeTuitionRequestPostRequest {
    /**
     * 
     * @type {PostponeTuitionFee}
     * @memberof CreatePostponeTuitionRequestPostRequest
     */
    postponeTuitionFee: PostponeTuitionFee;
}

/**
 * Check if a given object implements the CreatePostponeTuitionRequestPostRequest interface.
 */
export function instanceOfCreatePostponeTuitionRequestPostRequest(value: object): value is CreatePostponeTuitionRequestPostRequest {
    if (!('postponeTuitionFee' in value) || value['postponeTuitionFee'] === undefined) return false;
    return true;
}

export function CreatePostponeTuitionRequestPostRequestFromJSON(json: any): CreatePostponeTuitionRequestPostRequest {
    return CreatePostponeTuitionRequestPostRequestFromJSONTyped(json, false);
}

export function CreatePostponeTuitionRequestPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreatePostponeTuitionRequestPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'postponeTuitionFee': PostponeTuitionFeeFromJSON(json['postponeTuitionFee']),
    };
}

export function CreatePostponeTuitionRequestPostRequestToJSON(json: any): CreatePostponeTuitionRequestPostRequest {
    return CreatePostponeTuitionRequestPostRequestToJSONTyped(json, false);
}

export function CreatePostponeTuitionRequestPostRequestToJSONTyped(value?: CreatePostponeTuitionRequestPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'postponeTuitionFee': PostponeTuitionFeeToJSON(value['postponeTuitionFee']),
    };
}

