/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStudentResponse
 */
export interface CreateStudentResponse {
    /**
     * 
     * @type {number}
     * @memberof CreateStudentResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentResponse
     */
    studentCode: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentResponse
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreateStudentResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the CreateStudentResponse interface.
 */
export function instanceOfCreateStudentResponse(value: object): value is CreateStudentResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('studentCode' in value) || value['studentCode'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function CreateStudentResponseFromJSON(json: any): CreateStudentResponse {
    return CreateStudentResponseFromJSONTyped(json, false);
}

export function CreateStudentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStudentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'studentCode': json['studentCode'],
        'message': json['message'],
        'success': json['success'],
    };
}

export function CreateStudentResponseToJSON(json: any): CreateStudentResponse {
    return CreateStudentResponseToJSONTyped(json, false);
}

export function CreateStudentResponseToJSONTyped(value?: CreateStudentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'studentCode': value['studentCode'],
        'message': value['message'],
        'success': value['success'],
    };
}

