/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateStudentRequest
 */
export interface CreateStudentRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    studentCode: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    campusCode: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    facultyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    majorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    departmentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    section?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateStudentRequest
     */
    advisorCode?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateStudentRequest
     */
    studentStatusId: number;
}

/**
 * Check if a given object implements the CreateStudentRequest interface.
 */
export function instanceOfCreateStudentRequest(value: object): value is CreateStudentRequest {
    if (!('studentCode' in value) || value['studentCode'] === undefined) return false;
    if (!('campusCode' in value) || value['campusCode'] === undefined) return false;
    if (!('studentStatusId' in value) || value['studentStatusId'] === undefined) return false;
    return true;
}

export function CreateStudentRequestFromJSON(json: any): CreateStudentRequest {
    return CreateStudentRequestFromJSONTyped(json, false);
}

export function CreateStudentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateStudentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'studentCode': json['studentCode'],
        'campusCode': json['campusCode'],
        'facultyCode': json['facultyCode'] == null ? undefined : json['facultyCode'],
        'majorCode': json['majorCode'] == null ? undefined : json['majorCode'],
        'departmentCode': json['departmentCode'] == null ? undefined : json['departmentCode'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'section': json['section'] == null ? undefined : json['section'],
        'advisorCode': json['advisorCode'] == null ? undefined : json['advisorCode'],
        'studentStatusId': json['studentStatusId'],
    };
}

export function CreateStudentRequestToJSON(json: any): CreateStudentRequest {
    return CreateStudentRequestToJSONTyped(json, false);
}

export function CreateStudentRequestToJSONTyped(value?: CreateStudentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studentCode': value['studentCode'],
        'campusCode': value['campusCode'],
        'facultyCode': value['facultyCode'],
        'majorCode': value['majorCode'],
        'departmentCode': value['departmentCode'],
        'phone': value['phone'],
        'email': value['email'],
        'section': value['section'],
        'advisorCode': value['advisorCode'],
        'studentStatusId': value['studentStatusId'],
    };
}

