/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DashboardTableItem } from './DashboardTableItem';
import {
    DashboardTableItemFromJSON,
    DashboardTableItemFromJSONTyped,
    DashboardTableItemToJSON,
    DashboardTableItemToJSONTyped,
} from './DashboardTableItem';

/**
 * 
 * @export
 * @interface DashboardRequestListResponse
 */
export interface DashboardRequestListResponse {
    /**
     * 
     * @type {Array<DashboardTableItem>}
     * @memberof DashboardRequestListResponse
     */
    items: Array<DashboardTableItem>;
    /**
     * 
     * @type {number}
     * @memberof DashboardRequestListResponse
     */
    total: number;
}

/**
 * Check if a given object implements the DashboardRequestListResponse interface.
 */
export function instanceOfDashboardRequestListResponse(value: object): value is DashboardRequestListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function DashboardRequestListResponseFromJSON(json: any): DashboardRequestListResponse {
    return DashboardRequestListResponseFromJSONTyped(json, false);
}

export function DashboardRequestListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardRequestListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(DashboardTableItemFromJSON)),
        'total': json['total'],
    };
}

export function DashboardRequestListResponseToJSON(json: any): DashboardRequestListResponse {
    return DashboardRequestListResponseToJSONTyped(json, false);
}

export function DashboardRequestListResponseToJSONTyped(value?: DashboardRequestListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(DashboardTableItemToJSON)),
        'total': value['total'],
    };
}

