/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DashboardTableItem
 */
export interface DashboardTableItem {
    /**
     * 
     * @type {string}
     * @memberof DashboardTableItem
     */
    key: string;
    /**
     * 
     * @type {number}
     * @memberof DashboardTableItem
     */
    no: number;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableItem
     */
    documentDate: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableItem
     */
    term: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableItem
     */
    academicYear: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableItem
     */
    requestType: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableItem
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof DashboardTableItem
     */
    statusColor?: string;
}

/**
 * Check if a given object implements the DashboardTableItem interface.
 */
export function instanceOfDashboardTableItem(value: object): value is DashboardTableItem {
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('no' in value) || value['no'] === undefined) return false;
    if (!('documentDate' in value) || value['documentDate'] === undefined) return false;
    if (!('term' in value) || value['term'] === undefined) return false;
    if (!('academicYear' in value) || value['academicYear'] === undefined) return false;
    if (!('requestType' in value) || value['requestType'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function DashboardTableItemFromJSON(json: any): DashboardTableItem {
    return DashboardTableItemFromJSONTyped(json, false);
}

export function DashboardTableItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardTableItem {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'no': json['no'],
        'documentDate': json['documentDate'],
        'term': json['term'],
        'academicYear': json['academicYear'],
        'requestType': json['requestType'],
        'status': json['status'],
        'statusColor': json['statusColor'] == null ? undefined : json['statusColor'],
    };
}

export function DashboardTableItemToJSON(json: any): DashboardTableItem {
    return DashboardTableItemToJSONTyped(json, false);
}

export function DashboardTableItemToJSONTyped(value?: DashboardTableItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'no': value['no'],
        'documentDate': value['documentDate'],
        'term': value['term'],
        'academicYear': value['academicYear'],
        'requestType': value['requestType'],
        'status': value['status'],
        'statusColor': value['statusColor'],
    };
}

