/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DashboardSummaryItem
 */
export interface DashboardSummaryItem {
    /**
     * 
     * @type {string}
     * @memberof DashboardSummaryItem
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof DashboardSummaryItem
     */
    value: number;
    /**
     * 
     * @type {string}
     * @memberof DashboardSummaryItem
     */
    color?: string;
}

/**
 * Check if a given object implements the DashboardSummaryItem interface.
 */
export function instanceOfDashboardSummaryItem(value: object): value is DashboardSummaryItem {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function DashboardSummaryItemFromJSON(json: any): DashboardSummaryItem {
    return DashboardSummaryItemFromJSONTyped(json, false);
}

export function DashboardSummaryItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardSummaryItem {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
        'color': json['color'] == null ? undefined : json['color'],
    };
}

export function DashboardSummaryItemToJSON(json: any): DashboardSummaryItem {
    return DashboardSummaryItemToJSONTyped(json, false);
}

export function DashboardSummaryItemToJSONTyped(value?: DashboardSummaryItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'value': value['value'],
        'color': value['color'],
    };
}

