/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteUser200Response
 */
export interface DeleteUser200Response {
    /**
     * 
     * @type {string}
     * @memberof DeleteUser200Response
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof DeleteUser200Response
     */
    success: boolean;
}

/**
 * Check if a given object implements the DeleteUser200Response interface.
 */
export function instanceOfDeleteUser200Response(value: object): value is DeleteUser200Response {
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function DeleteUser200ResponseFromJSON(json: any): DeleteUser200Response {
    return DeleteUser200ResponseFromJSONTyped(json, false);
}

export function DeleteUser200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUser200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'success': json['success'],
    };
}

export function DeleteUser200ResponseToJSON(json: any): DeleteUser200Response {
    return DeleteUser200ResponseToJSONTyped(json, false);
}

export function DeleteUser200ResponseToJSONTyped(value?: DeleteUser200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'success': value['success'],
    };
}

