/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ExportStudentsData200Response
 */
export interface ExportStudentsData200Response {
    /**
     * 
     * @type {string}
     * @memberof ExportStudentsData200Response
     */
    filename: string;
    /**
     * 
     * @type {string}
     * @memberof ExportStudentsData200Response
     */
    csvData: string;
}

/**
 * Check if a given object implements the ExportStudentsData200Response interface.
 */
export function instanceOfExportStudentsData200Response(value: object): value is ExportStudentsData200Response {
    if (!('filename' in value) || value['filename'] === undefined) return false;
    if (!('csvData' in value) || value['csvData'] === undefined) return false;
    return true;
}

export function ExportStudentsData200ResponseFromJSON(json: any): ExportStudentsData200Response {
    return ExportStudentsData200ResponseFromJSONTyped(json, false);
}

export function ExportStudentsData200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExportStudentsData200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'],
        'csvData': json['csvData'],
    };
}

export function ExportStudentsData200ResponseToJSON(json: any): ExportStudentsData200Response {
    return ExportStudentsData200ResponseToJSONTyped(json, false);
}

export function ExportStudentsData200ResponseToJSONTyped(value?: ExportStudentsData200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'filename': value['filename'],
        'csvData': value['csvData'],
    };
}

