/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneralRequestDetailRequest
 */
export interface GeneralRequestDetailRequest {
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestDetailRequest
     */
    headerUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestDetailRequest
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestDetailRequest
     */
    cause?: string;
}

/**
 * Check if a given object implements the GeneralRequestDetailRequest interface.
 */
export function instanceOfGeneralRequestDetailRequest(value: object): value is GeneralRequestDetailRequest {
    return true;
}

export function GeneralRequestDetailRequestFromJSON(json: any): GeneralRequestDetailRequest {
    return GeneralRequestDetailRequestFromJSONTyped(json, false);
}

export function GeneralRequestDetailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralRequestDetailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'headerUuid': json['headerUuid'] == null ? undefined : json['headerUuid'],
        'topic': json['topic'] == null ? undefined : json['topic'],
        'cause': json['cause'] == null ? undefined : json['cause'],
    };
}

export function GeneralRequestDetailRequestToJSON(json: any): GeneralRequestDetailRequest {
    return GeneralRequestDetailRequestToJSONTyped(json, false);
}

export function GeneralRequestDetailRequestToJSONTyped(value?: GeneralRequestDetailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headerUuid': value['headerUuid'],
        'topic': value['topic'],
        'cause': value['cause'],
    };
}

