/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneralRequestResponse
 */
export interface GeneralRequestResponse {
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestResponse
     */
    headerUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestResponse
     */
    studentName?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestResponse
     */
    studentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestResponse
     */
    facultyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestResponse
     */
    majorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestResponse
     */
    phone?: string;
}

/**
 * Check if a given object implements the GeneralRequestResponse interface.
 */
export function instanceOfGeneralRequestResponse(value: object): value is GeneralRequestResponse {
    return true;
}

export function GeneralRequestResponseFromJSON(json: any): GeneralRequestResponse {
    return GeneralRequestResponseFromJSONTyped(json, false);
}

export function GeneralRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'headerUuid': json['headerUuid'] == null ? undefined : json['headerUuid'],
        'studentName': json['studentName'] == null ? undefined : json['studentName'],
        'studentCode': json['studentCode'] == null ? undefined : json['studentCode'],
        'facultyCode': json['facultyCode'] == null ? undefined : json['facultyCode'],
        'majorCode': json['majorCode'] == null ? undefined : json['majorCode'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
    };
}

export function GeneralRequestResponseToJSON(json: any): GeneralRequestResponse {
    return GeneralRequestResponseToJSONTyped(json, false);
}

export function GeneralRequestResponseToJSONTyped(value?: GeneralRequestResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headerUuid': value['headerUuid'],
        'studentName': value['studentName'],
        'studentCode': value['studentCode'],
        'facultyCode': value['facultyCode'],
        'majorCode': value['majorCode'],
        'email': value['email'],
        'phone': value['phone'],
    };
}

