/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneralRequestDetailResponse
 */
export interface GeneralRequestDetailResponse {
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestDetailResponse
     */
    headerUuid?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestDetailResponse
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestDetailResponse
     */
    cause?: string;
}

/**
 * Check if a given object implements the GeneralRequestDetailResponse interface.
 */
export function instanceOfGeneralRequestDetailResponse(value: object): value is GeneralRequestDetailResponse {
    return true;
}

export function GeneralRequestDetailResponseFromJSON(json: any): GeneralRequestDetailResponse {
    return GeneralRequestDetailResponseFromJSONTyped(json, false);
}

export function GeneralRequestDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralRequestDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'headerUuid': json['headerUuid'] == null ? undefined : json['headerUuid'],
        'topic': json['topic'] == null ? undefined : json['topic'],
        'cause': json['cause'] == null ? undefined : json['cause'],
    };
}

export function GeneralRequestDetailResponseToJSON(json: any): GeneralRequestDetailResponse {
    return GeneralRequestDetailResponseToJSONTyped(json, false);
}

export function GeneralRequestDetailResponseToJSONTyped(value?: GeneralRequestDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'headerUuid': value['headerUuid'],
        'topic': value['topic'],
        'cause': value['cause'],
    };
}

