/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneralRequestRequest
 */
export interface GeneralRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestRequest
     */
    studentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestRequest
     */
    topic?: string;
    /**
     * 
     * @type {string}
     * @memberof GeneralRequestRequest
     */
    cause?: string;
}

/**
 * Check if a given object implements the GeneralRequestRequest interface.
 */
export function instanceOfGeneralRequestRequest(value: object): value is GeneralRequestRequest {
    return true;
}

export function GeneralRequestRequestFromJSON(json: any): GeneralRequestRequest {
    return GeneralRequestRequestFromJSONTyped(json, false);
}

export function GeneralRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneralRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'studentCode': json['studentCode'] == null ? undefined : json['studentCode'],
        'topic': json['topic'] == null ? undefined : json['topic'],
        'cause': json['cause'] == null ? undefined : json['cause'],
    };
}

export function GeneralRequestRequestToJSON(json: any): GeneralRequestRequest {
    return GeneralRequestRequestToJSONTyped(json, false);
}

export function GeneralRequestRequestToJSONTyped(value?: GeneralRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studentCode': value['studentCode'],
        'topic': value['topic'],
        'cause': value['cause'],
    };
}

