/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserResponse } from './UserResponse';
import {
    UserResponseFromJSON,
    UserResponseFromJSONTyped,
    UserResponseToJSON,
    UserResponseToJSONTyped,
} from './UserResponse';

/**
 * 
 * @export
 * @interface GetAllUsersResponse
 */
export interface GetAllUsersResponse {
    /**
     * 
     * @type {Array<UserResponse>}
     * @memberof GetAllUsersResponse
     */
    users: Array<UserResponse>;
    /**
     * 
     * @type {number}
     * @memberof GetAllUsersResponse
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof GetAllUsersResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof GetAllUsersResponse
     */
    pageSize: number;
}

/**
 * Check if a given object implements the GetAllUsersResponse interface.
 */
export function instanceOfGetAllUsersResponse(value: object): value is GetAllUsersResponse {
    if (!('users' in value) || value['users'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    return true;
}

export function GetAllUsersResponseFromJSON(json: any): GetAllUsersResponse {
    return GetAllUsersResponseFromJSONTyped(json, false);
}

export function GetAllUsersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAllUsersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'users': ((json['users'] as Array<any>).map(UserResponseFromJSON)),
        'totalCount': json['totalCount'],
        'page': json['page'],
        'pageSize': json['pageSize'],
    };
}

export function GetAllUsersResponseToJSON(json: any): GetAllUsersResponse {
    return GetAllUsersResponseToJSONTyped(json, false);
}

export function GetAllUsersResponseToJSONTyped(value?: GetAllUsersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'users': ((value['users'] as Array<any>).map(UserResponseToJSON)),
        'totalCount': value['totalCount'],
        'page': value['page'],
        'pageSize': value['pageSize'],
    };
}

