/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RequestTypeResponse } from './RequestTypeResponse';
import {
    RequestTypeResponseFromJSON,
    RequestTypeResponseFromJSONTyped,
    RequestTypeResponseToJSON,
    RequestTypeResponseToJSONTyped,
} from './RequestTypeResponse';

/**
 * 
 * @export
 * @interface GetRequestTypesResponse
 */
export interface GetRequestTypesResponse {
    /**
     * 
     * @type {Array<RequestTypeResponse>}
     * @memberof GetRequestTypesResponse
     */
    data: Array<RequestTypeResponse>;
    /**
     * 
     * @type {number}
     * @memberof GetRequestTypesResponse
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof GetRequestTypesResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof GetRequestTypesResponse
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof GetRequestTypesResponse
     */
    totalPages: number;
}

/**
 * Check if a given object implements the GetRequestTypesResponse interface.
 */
export function instanceOfGetRequestTypesResponse(value: object): value is GetRequestTypesResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('totalPages' in value) || value['totalPages'] === undefined) return false;
    return true;
}

export function GetRequestTypesResponseFromJSON(json: any): GetRequestTypesResponse {
    return GetRequestTypesResponseFromJSONTyped(json, false);
}

export function GetRequestTypesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetRequestTypesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(RequestTypeResponseFromJSON)),
        'total': json['total'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'totalPages': json['totalPages'],
    };
}

export function GetRequestTypesResponseToJSON(json: any): GetRequestTypesResponse {
    return GetRequestTypesResponseToJSONTyped(json, false);
}

export function GetRequestTypesResponseToJSONTyped(value?: GetRequestTypesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(RequestTypeResponseToJSON)),
        'total': value['total'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalPages': value['totalPages'],
    };
}

