/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportStudentsDataRequest
 */
export interface ImportStudentsDataRequest {
    /**
     * 
     * @type {string}
     * @memberof ImportStudentsDataRequest
     */
    csvData: string;
}

/**
 * Check if a given object implements the ImportStudentsDataRequest interface.
 */
export function instanceOfImportStudentsDataRequest(value: object): value is ImportStudentsDataRequest {
    if (!('csvData' in value) || value['csvData'] === undefined) return false;
    return true;
}

export function ImportStudentsDataRequestFromJSON(json: any): ImportStudentsDataRequest {
    return ImportStudentsDataRequestFromJSONTyped(json, false);
}

export function ImportStudentsDataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportStudentsDataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'csvData': json['csvData'],
    };
}

export function ImportStudentsDataRequestToJSON(json: any): ImportStudentsDataRequest {
    return ImportStudentsDataRequestToJSONTyped(json, false);
}

export function ImportStudentsDataRequestToJSONTyped(value?: ImportStudentsDataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'csvData': value['csvData'],
    };
}

