/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportStudentsData200Response
 */
export interface ImportStudentsData200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof ImportStudentsData200Response
     */
    errors: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof ImportStudentsData200Response
     */
    errorCount: number;
    /**
     * 
     * @type {number}
     * @memberof ImportStudentsData200Response
     */
    successCount: number;
}

/**
 * Check if a given object implements the ImportStudentsData200Response interface.
 */
export function instanceOfImportStudentsData200Response(value: object): value is ImportStudentsData200Response {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if (!('errorCount' in value) || value['errorCount'] === undefined) return false;
    if (!('successCount' in value) || value['successCount'] === undefined) return false;
    return true;
}

export function ImportStudentsData200ResponseFromJSON(json: any): ImportStudentsData200Response {
    return ImportStudentsData200ResponseFromJSONTyped(json, false);
}

export function ImportStudentsData200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportStudentsData200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'],
        'errorCount': json['errorCount'],
        'successCount': json['successCount'],
    };
}

export function ImportStudentsData200ResponseToJSON(json: any): ImportStudentsData200Response {
    return ImportStudentsData200ResponseToJSONTyped(json, false);
}

export function ImportStudentsData200ResponseToJSONTyped(value?: ImportStudentsData200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'],
        'errorCount': value['errorCount'],
        'successCount': value['successCount'],
    };
}

