/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogoutRequest
 */
export interface LogoutRequest {
    /**
     * 
     * @type {number}
     * @memberof LogoutRequest
     */
    userId: number;
}

/**
 * Check if a given object implements the LogoutRequest interface.
 */
export function instanceOfLogoutRequest(value: object): value is LogoutRequest {
    if (!('userId' in value) || value['userId'] === undefined) return false;
    return true;
}

export function LogoutRequestFromJSON(json: any): LogoutRequest {
    return LogoutRequestFromJSONTyped(json, false);
}

export function LogoutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogoutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
    };
}

export function LogoutRequestToJSON(json: any): LogoutRequest {
    return LogoutRequestToJSONTyped(json, false);
}

export function LogoutRequestToJSONTyped(value?: LogoutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
    };
}

