/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MasterValueDetailResponse
 */
export interface MasterValueDetailResponse {
    /**
     * 
     * @type {number}
     * @memberof MasterValueDetailResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MasterValueDetailResponse
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof MasterValueDetailResponse
     */
    masterValueDetailCode?: string;
    /**
     * 
     * @type {string}
     * @memberof MasterValueDetailResponse
     */
    descriptionTh?: string;
    /**
     * 
     * @type {string}
     * @memberof MasterValueDetailResponse
     */
    descriptionEn?: string;
    /**
     * 
     * @type {number}
     * @memberof MasterValueDetailResponse
     */
    sequence?: number;
    /**
     * 
     * @type {number}
     * @memberof MasterValueDetailResponse
     */
    masterValueHeaderId?: number;
}

/**
 * Check if a given object implements the MasterValueDetailResponse interface.
 */
export function instanceOfMasterValueDetailResponse(value: object): value is MasterValueDetailResponse {
    return true;
}

export function MasterValueDetailResponseFromJSON(json: any): MasterValueDetailResponse {
    return MasterValueDetailResponseFromJSONTyped(json, false);
}

export function MasterValueDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MasterValueDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'masterValueDetailCode': json['masterValueDetailCode'] == null ? undefined : json['masterValueDetailCode'],
        'descriptionTh': json['descriptionTh'] == null ? undefined : json['descriptionTh'],
        'descriptionEn': json['descriptionEn'] == null ? undefined : json['descriptionEn'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'masterValueHeaderId': json['masterValueHeaderId'] == null ? undefined : json['masterValueHeaderId'],
    };
}

export function MasterValueDetailResponseToJSON(json: any): MasterValueDetailResponse {
    return MasterValueDetailResponseToJSONTyped(json, false);
}

export function MasterValueDetailResponseToJSONTyped(value?: MasterValueDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uuid': value['uuid'],
        'masterValueDetailCode': value['masterValueDetailCode'],
        'descriptionTh': value['descriptionTh'],
        'descriptionEn': value['descriptionEn'],
        'sequence': value['sequence'],
        'masterValueHeaderId': value['masterValueHeaderId'],
    };
}

