/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MasterValueHeaderResponse
 */
export interface MasterValueHeaderResponse {
    /**
     * 
     * @type {number}
     * @memberof MasterValueHeaderResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MasterValueHeaderResponse
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof MasterValueHeaderResponse
     */
    masterValueCode?: string;
    /**
     * 
     * @type {string}
     * @memberof MasterValueHeaderResponse
     */
    masterValueName?: string;
}

/**
 * Check if a given object implements the MasterValueHeaderResponse interface.
 */
export function instanceOfMasterValueHeaderResponse(value: object): value is MasterValueHeaderResponse {
    return true;
}

export function MasterValueHeaderResponseFromJSON(json: any): MasterValueHeaderResponse {
    return MasterValueHeaderResponseFromJSONTyped(json, false);
}

export function MasterValueHeaderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MasterValueHeaderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'masterValueCode': json['masterValueCode'] == null ? undefined : json['masterValueCode'],
        'masterValueName': json['masterValueName'] == null ? undefined : json['masterValueName'],
    };
}

export function MasterValueHeaderResponseToJSON(json: any): MasterValueHeaderResponse {
    return MasterValueHeaderResponseToJSONTyped(json, false);
}

export function MasterValueHeaderResponseToJSONTyped(value?: MasterValueHeaderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uuid': value['uuid'],
        'masterValueCode': value['masterValueCode'],
        'masterValueName': value['masterValueName'],
    };
}

