/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PostponeTuitionFee
 */
export interface PostponeTuitionFee {
    /**
     * 
     * @type {string}
     * @memberof PostponeTuitionFee
     */
    semesterCode?: string;
    /**
     * 
     * @type {number}
     * @memberof PostponeTuitionFee
     */
    academicYear?: number;
    /**
     * 
     * @type {number}
     * @memberof PostponeTuitionFee
     */
    feeAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof PostponeTuitionFee
     */
    hasOutstandingDept?: string;
    /**
     * 
     * @type {string}
     * @memberof PostponeTuitionFee
     */
    deptSemesterCode?: string;
    /**
     * 
     * @type {number}
     * @memberof PostponeTuitionFee
     */
    deptAcademicYear?: number;
    /**
     * 
     * @type {number}
     * @memberof PostponeTuitionFee
     */
    deptAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof PostponeTuitionFee
     */
    cause?: string;
    /**
     * 
     * @type {Date}
     * @memberof PostponeTuitionFee
     */
    expectedPayDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof PostponeTuitionFee
     */
    studentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PostponeTuitionFee
     */
    parentPhone?: string;
}

/**
 * Check if a given object implements the PostponeTuitionFee interface.
 */
export function instanceOfPostponeTuitionFee(value: object): value is PostponeTuitionFee {
    return true;
}

export function PostponeTuitionFeeFromJSON(json: any): PostponeTuitionFee {
    return PostponeTuitionFeeFromJSONTyped(json, false);
}

export function PostponeTuitionFeeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostponeTuitionFee {
    if (json == null) {
        return json;
    }
    return {
        
        'semesterCode': json['semesterCode'] == null ? undefined : json['semesterCode'],
        'academicYear': json['academicYear'] == null ? undefined : json['academicYear'],
        'feeAmount': json['feeAmount'] == null ? undefined : json['feeAmount'],
        'hasOutstandingDept': json['hasOutstandingDept'] == null ? undefined : json['hasOutstandingDept'],
        'deptSemesterCode': json['deptSemesterCode'] == null ? undefined : json['deptSemesterCode'],
        'deptAcademicYear': json['deptAcademicYear'] == null ? undefined : json['deptAcademicYear'],
        'deptAmount': json['deptAmount'] == null ? undefined : json['deptAmount'],
        'cause': json['cause'] == null ? undefined : json['cause'],
        'expectedPayDate': json['expectedPayDate'] == null ? undefined : (new Date(json['expectedPayDate'])),
        'studentCode': json['studentCode'] == null ? undefined : json['studentCode'],
        'parentPhone': json['parentPhone'] == null ? undefined : json['parentPhone'],
    };
}

export function PostponeTuitionFeeToJSON(json: any): PostponeTuitionFee {
    return PostponeTuitionFeeToJSONTyped(json, false);
}

export function PostponeTuitionFeeToJSONTyped(value?: PostponeTuitionFee | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'semesterCode': value['semesterCode'],
        'academicYear': value['academicYear'],
        'feeAmount': value['feeAmount'],
        'hasOutstandingDept': value['hasOutstandingDept'],
        'deptSemesterCode': value['deptSemesterCode'],
        'deptAcademicYear': value['deptAcademicYear'],
        'deptAmount': value['deptAmount'],
        'cause': value['cause'],
        'expectedPayDate': value['expectedPayDate'] == null ? undefined : ((value['expectedPayDate']).toISOString()),
        'studentCode': value['studentCode'],
        'parentPhone': value['parentPhone'],
    };
}

