/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestTypeResponse
 */
export interface RequestTypeResponse {
    /**
     * 
     * @type {number}
     * @memberof RequestTypeResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RequestTypeResponse
     */
    uuid?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestTypeResponse
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestTypeResponse
     */
    nameTh?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestTypeResponse
     */
    nameEn?: string;
    /**
     * 
     * @type {string}
     * @memberof RequestTypeResponse
     */
    status?: string;
    /**
     * 
     * @type {Date}
     * @memberof RequestTypeResponse
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof RequestTypeResponse
     */
    createdBy?: string;
    /**
     * 
     * @type {Date}
     * @memberof RequestTypeResponse
     */
    updatedDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof RequestTypeResponse
     */
    updatedBy?: string;
    /**
     * 
     * @type {number}
     * @memberof RequestTypeResponse
     */
    version?: number;
}

/**
 * Check if a given object implements the RequestTypeResponse interface.
 */
export function instanceOfRequestTypeResponse(value: object): value is RequestTypeResponse {
    return true;
}

export function RequestTypeResponseFromJSON(json: any): RequestTypeResponse {
    return RequestTypeResponseFromJSONTyped(json, false);
}

export function RequestTypeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestTypeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
        'code': json['code'] == null ? undefined : json['code'],
        'nameTh': json['nameTh'] == null ? undefined : json['nameTh'],
        'nameEn': json['nameEn'] == null ? undefined : json['nameEn'],
        'status': json['status'] == null ? undefined : json['status'],
        'createdDate': json['createdDate'] == null ? undefined : (new Date(json['createdDate'])),
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'updatedDate': json['updatedDate'] == null ? undefined : (new Date(json['updatedDate'])),
        'updatedBy': json['updatedBy'] == null ? undefined : json['updatedBy'],
        'version': json['version'] == null ? undefined : json['version'],
    };
}

export function RequestTypeResponseToJSON(json: any): RequestTypeResponse {
    return RequestTypeResponseToJSONTyped(json, false);
}

export function RequestTypeResponseToJSONTyped(value?: RequestTypeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'uuid': value['uuid'],
        'code': value['code'],
        'nameTh': value['nameTh'],
        'nameEn': value['nameEn'],
        'status': value['status'],
        'createdDate': value['createdDate'] == null ? undefined : ((value['createdDate']).toISOString()),
        'createdBy': value['createdBy'],
        'updatedDate': value['updatedDate'] == null ? undefined : ((value['updatedDate']).toISOString()),
        'updatedBy': value['updatedBy'],
        'version': value['version'],
    };
}

