/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveMasterValueDetailPostRequest
 */
export interface SaveMasterValueDetailPostRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueDetailPostRequest
     */
    masterValueDetailCode: string;
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueDetailPostRequest
     */
    descriptionTh?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueDetailPostRequest
     */
    descriptionEn?: string;
    /**
     * 
     * @type {number}
     * @memberof SaveMasterValueDetailPostRequest
     */
    sequence?: number;
    /**
     * 
     * @type {number}
     * @memberof SaveMasterValueDetailPostRequest
     */
    masterValueHeaderId: number;
}

/**
 * Check if a given object implements the SaveMasterValueDetailPostRequest interface.
 */
export function instanceOfSaveMasterValueDetailPostRequest(value: object): value is SaveMasterValueDetailPostRequest {
    if (!('masterValueDetailCode' in value) || value['masterValueDetailCode'] === undefined) return false;
    if (!('masterValueHeaderId' in value) || value['masterValueHeaderId'] === undefined) return false;
    return true;
}

export function SaveMasterValueDetailPostRequestFromJSON(json: any): SaveMasterValueDetailPostRequest {
    return SaveMasterValueDetailPostRequestFromJSONTyped(json, false);
}

export function SaveMasterValueDetailPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveMasterValueDetailPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'masterValueDetailCode': json['masterValueDetailCode'],
        'descriptionTh': json['descriptionTh'] == null ? undefined : json['descriptionTh'],
        'descriptionEn': json['descriptionEn'] == null ? undefined : json['descriptionEn'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'masterValueHeaderId': json['masterValueHeaderId'],
    };
}

export function SaveMasterValueDetailPostRequestToJSON(json: any): SaveMasterValueDetailPostRequest {
    return SaveMasterValueDetailPostRequestToJSONTyped(json, false);
}

export function SaveMasterValueDetailPostRequestToJSONTyped(value?: SaveMasterValueDetailPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'masterValueDetailCode': value['masterValueDetailCode'],
        'descriptionTh': value['descriptionTh'],
        'descriptionEn': value['descriptionEn'],
        'sequence': value['sequence'],
        'masterValueHeaderId': value['masterValueHeaderId'],
    };
}

