/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveMasterValueDetailRequest
 */
export interface SaveMasterValueDetailRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveMasterValueDetailRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueDetailRequest
     */
    masterValueDetailCode?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueDetailRequest
     */
    descriptionTh?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueDetailRequest
     */
    descriptionEn?: string;
    /**
     * 
     * @type {number}
     * @memberof SaveMasterValueDetailRequest
     */
    sequence?: number;
    /**
     * 
     * @type {number}
     * @memberof SaveMasterValueDetailRequest
     */
    masterValueHeaderId?: number;
}

/**
 * Check if a given object implements the SaveMasterValueDetailRequest interface.
 */
export function instanceOfSaveMasterValueDetailRequest(value: object): value is SaveMasterValueDetailRequest {
    return true;
}

export function SaveMasterValueDetailRequestFromJSON(json: any): SaveMasterValueDetailRequest {
    return SaveMasterValueDetailRequestFromJSONTyped(json, false);
}

export function SaveMasterValueDetailRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveMasterValueDetailRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'masterValueDetailCode': json['masterValueDetailCode'] == null ? undefined : json['masterValueDetailCode'],
        'descriptionTh': json['descriptionTh'] == null ? undefined : json['descriptionTh'],
        'descriptionEn': json['descriptionEn'] == null ? undefined : json['descriptionEn'],
        'sequence': json['sequence'] == null ? undefined : json['sequence'],
        'masterValueHeaderId': json['masterValueHeaderId'] == null ? undefined : json['masterValueHeaderId'],
    };
}

export function SaveMasterValueDetailRequestToJSON(json: any): SaveMasterValueDetailRequest {
    return SaveMasterValueDetailRequestToJSONTyped(json, false);
}

export function SaveMasterValueDetailRequestToJSONTyped(value?: SaveMasterValueDetailRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'masterValueDetailCode': value['masterValueDetailCode'],
        'descriptionTh': value['descriptionTh'],
        'descriptionEn': value['descriptionEn'],
        'sequence': value['sequence'],
        'masterValueHeaderId': value['masterValueHeaderId'],
    };
}

