/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveMasterValueHeaderRequest
 */
export interface SaveMasterValueHeaderRequest {
    /**
     * 
     * @type {number}
     * @memberof SaveMasterValueHeaderRequest
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueHeaderRequest
     */
    masterValueCode?: string;
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueHeaderRequest
     */
    masterValueName?: string;
}

/**
 * Check if a given object implements the SaveMasterValueHeaderRequest interface.
 */
export function instanceOfSaveMasterValueHeaderRequest(value: object): value is SaveMasterValueHeaderRequest {
    return true;
}

export function SaveMasterValueHeaderRequestFromJSON(json: any): SaveMasterValueHeaderRequest {
    return SaveMasterValueHeaderRequestFromJSONTyped(json, false);
}

export function SaveMasterValueHeaderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveMasterValueHeaderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'masterValueCode': json['masterValueCode'] == null ? undefined : json['masterValueCode'],
        'masterValueName': json['masterValueName'] == null ? undefined : json['masterValueName'],
    };
}

export function SaveMasterValueHeaderRequestToJSON(json: any): SaveMasterValueHeaderRequest {
    return SaveMasterValueHeaderRequestToJSONTyped(json, false);
}

export function SaveMasterValueHeaderRequestToJSONTyped(value?: SaveMasterValueHeaderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'masterValueCode': value['masterValueCode'],
        'masterValueName': value['masterValueName'],
    };
}

