/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SaveMasterValueHeaderPostRequest
 */
export interface SaveMasterValueHeaderPostRequest {
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueHeaderPostRequest
     */
    masterValueCode: string;
    /**
     * 
     * @type {string}
     * @memberof SaveMasterValueHeaderPostRequest
     */
    masterValueName?: string;
}

/**
 * Check if a given object implements the SaveMasterValueHeaderPostRequest interface.
 */
export function instanceOfSaveMasterValueHeaderPostRequest(value: object): value is SaveMasterValueHeaderPostRequest {
    if (!('masterValueCode' in value) || value['masterValueCode'] === undefined) return false;
    return true;
}

export function SaveMasterValueHeaderPostRequestFromJSON(json: any): SaveMasterValueHeaderPostRequest {
    return SaveMasterValueHeaderPostRequestFromJSONTyped(json, false);
}

export function SaveMasterValueHeaderPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SaveMasterValueHeaderPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'masterValueCode': json['masterValueCode'],
        'masterValueName': json['masterValueName'] == null ? undefined : json['masterValueName'],
    };
}

export function SaveMasterValueHeaderPostRequestToJSON(json: any): SaveMasterValueHeaderPostRequest {
    return SaveMasterValueHeaderPostRequestToJSONTyped(json, false);
}

export function SaveMasterValueHeaderPostRequestToJSONTyped(value?: SaveMasterValueHeaderPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'masterValueCode': value['masterValueCode'],
        'masterValueName': value['masterValueName'],
    };
}

