/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentSearchRequest
 */
export interface StudentSearchRequest {
    /**
     * 
     * @type {string}
     * @memberof StudentSearchRequest
     */
    searchTerm?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentSearchRequest
     */
    campusCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentSearchRequest
     */
    facultyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentSearchRequest
     */
    majorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentSearchRequest
     */
    section?: string;
    /**
     * 
     * @type {number}
     * @memberof StudentSearchRequest
     */
    studentStatusId?: number;
}

/**
 * Check if a given object implements the StudentSearchRequest interface.
 */
export function instanceOfStudentSearchRequest(value: object): value is StudentSearchRequest {
    return true;
}

export function StudentSearchRequestFromJSON(json: any): StudentSearchRequest {
    return StudentSearchRequestFromJSONTyped(json, false);
}

export function StudentSearchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentSearchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'searchTerm': json['searchTerm'] == null ? undefined : json['searchTerm'],
        'campusCode': json['campusCode'] == null ? undefined : json['campusCode'],
        'facultyCode': json['facultyCode'] == null ? undefined : json['facultyCode'],
        'majorCode': json['majorCode'] == null ? undefined : json['majorCode'],
        'section': json['section'] == null ? undefined : json['section'],
        'studentStatusId': json['studentStatusId'] == null ? undefined : json['studentStatusId'],
    };
}

export function StudentSearchRequestToJSON(json: any): StudentSearchRequest {
    return StudentSearchRequestToJSONTyped(json, false);
}

export function StudentSearchRequestToJSONTyped(value?: StudentSearchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'searchTerm': value['searchTerm'],
        'campusCode': value['campusCode'],
        'facultyCode': value['facultyCode'],
        'majorCode': value['majorCode'],
        'section': value['section'],
        'studentStatusId': value['studentStatusId'],
    };
}

