/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentStatisticsResponseStudentsByCampusInner
 */
export interface StudentStatisticsResponseStudentsByCampusInner {
    /**
     * 
     * @type {number}
     * @memberof StudentStatisticsResponseStudentsByCampusInner
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof StudentStatisticsResponseStudentsByCampusInner
     */
    campusCode: string;
}

/**
 * Check if a given object implements the StudentStatisticsResponseStudentsByCampusInner interface.
 */
export function instanceOfStudentStatisticsResponseStudentsByCampusInner(value: object): value is StudentStatisticsResponseStudentsByCampusInner {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('campusCode' in value) || value['campusCode'] === undefined) return false;
    return true;
}

export function StudentStatisticsResponseStudentsByCampusInnerFromJSON(json: any): StudentStatisticsResponseStudentsByCampusInner {
    return StudentStatisticsResponseStudentsByCampusInnerFromJSONTyped(json, false);
}

export function StudentStatisticsResponseStudentsByCampusInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentStatisticsResponseStudentsByCampusInner {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'campusCode': json['campusCode'],
    };
}

export function StudentStatisticsResponseStudentsByCampusInnerToJSON(json: any): StudentStatisticsResponseStudentsByCampusInner {
    return StudentStatisticsResponseStudentsByCampusInnerToJSONTyped(json, false);
}

export function StudentStatisticsResponseStudentsByCampusInnerToJSONTyped(value?: StudentStatisticsResponseStudentsByCampusInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'campusCode': value['campusCode'],
    };
}

