/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentStatisticsResponseStudentsByStatusInner
 */
export interface StudentStatisticsResponseStudentsByStatusInner {
    /**
     * 
     * @type {number}
     * @memberof StudentStatisticsResponseStudentsByStatusInner
     */
    count: number;
    /**
     * 
     * @type {number}
     * @memberof StudentStatisticsResponseStudentsByStatusInner
     */
    studentStatusId: number;
}

/**
 * Check if a given object implements the StudentStatisticsResponseStudentsByStatusInner interface.
 */
export function instanceOfStudentStatisticsResponseStudentsByStatusInner(value: object): value is StudentStatisticsResponseStudentsByStatusInner {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('studentStatusId' in value) || value['studentStatusId'] === undefined) return false;
    return true;
}

export function StudentStatisticsResponseStudentsByStatusInnerFromJSON(json: any): StudentStatisticsResponseStudentsByStatusInner {
    return StudentStatisticsResponseStudentsByStatusInnerFromJSONTyped(json, false);
}

export function StudentStatisticsResponseStudentsByStatusInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentStatisticsResponseStudentsByStatusInner {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'studentStatusId': json['studentStatusId'],
    };
}

export function StudentStatisticsResponseStudentsByStatusInnerToJSON(json: any): StudentStatisticsResponseStudentsByStatusInner {
    return StudentStatisticsResponseStudentsByStatusInnerToJSONTyped(json, false);
}

export function StudentStatisticsResponseStudentsByStatusInnerToJSONTyped(value?: StudentStatisticsResponseStudentsByStatusInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'studentStatusId': value['studentStatusId'],
    };
}

