/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudentSearchResponseFilters } from './StudentSearchResponseFilters';
import {
    StudentSearchResponseFiltersFromJSON,
    StudentSearchResponseFiltersFromJSONTyped,
    StudentSearchResponseFiltersToJSON,
    StudentSearchResponseFiltersToJSONTyped,
} from './StudentSearchResponseFilters';
import type { StudentResponse } from './StudentResponse';
import {
    StudentResponseFromJSON,
    StudentResponseFromJSONTyped,
    StudentResponseToJSON,
    StudentResponseToJSONTyped,
} from './StudentResponse';

/**
 * 
 * @export
 * @interface StudentSearchResponse
 */
export interface StudentSearchResponse {
    /**
     * 
     * @type {Array<StudentResponse>}
     * @memberof StudentSearchResponse
     */
    students: Array<StudentResponse>;
    /**
     * 
     * @type {number}
     * @memberof StudentSearchResponse
     */
    totalCount: number;
    /**
     * 
     * @type {number}
     * @memberof StudentSearchResponse
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof StudentSearchResponse
     */
    pageSize: number;
    /**
     * 
     * @type {StudentSearchResponseFilters}
     * @memberof StudentSearchResponse
     */
    filters: StudentSearchResponseFilters;
}

/**
 * Check if a given object implements the StudentSearchResponse interface.
 */
export function instanceOfStudentSearchResponse(value: object): value is StudentSearchResponse {
    if (!('students' in value) || value['students'] === undefined) return false;
    if (!('totalCount' in value) || value['totalCount'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('filters' in value) || value['filters'] === undefined) return false;
    return true;
}

export function StudentSearchResponseFromJSON(json: any): StudentSearchResponse {
    return StudentSearchResponseFromJSONTyped(json, false);
}

export function StudentSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentSearchResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'students': ((json['students'] as Array<any>).map(StudentResponseFromJSON)),
        'totalCount': json['totalCount'],
        'page': json['page'],
        'pageSize': json['pageSize'],
        'filters': StudentSearchResponseFiltersFromJSON(json['filters']),
    };
}

export function StudentSearchResponseToJSON(json: any): StudentSearchResponse {
    return StudentSearchResponseToJSONTyped(json, false);
}

export function StudentSearchResponseToJSONTyped(value?: StudentSearchResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'students': ((value['students'] as Array<any>).map(StudentResponseToJSON)),
        'totalCount': value['totalCount'],
        'page': value['page'],
        'pageSize': value['pageSize'],
        'filters': StudentSearchResponseFiltersToJSON(value['filters']),
    };
}

