/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentStatisticsResponseStudentsByMajorInner
 */
export interface StudentStatisticsResponseStudentsByMajorInner {
    /**
     * 
     * @type {number}
     * @memberof StudentStatisticsResponseStudentsByMajorInner
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof StudentStatisticsResponseStudentsByMajorInner
     */
    majorCode: string;
}

/**
 * Check if a given object implements the StudentStatisticsResponseStudentsByMajorInner interface.
 */
export function instanceOfStudentStatisticsResponseStudentsByMajorInner(value: object): value is StudentStatisticsResponseStudentsByMajorInner {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('majorCode' in value) || value['majorCode'] === undefined) return false;
    return true;
}

export function StudentStatisticsResponseStudentsByMajorInnerFromJSON(json: any): StudentStatisticsResponseStudentsByMajorInner {
    return StudentStatisticsResponseStudentsByMajorInnerFromJSONTyped(json, false);
}

export function StudentStatisticsResponseStudentsByMajorInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentStatisticsResponseStudentsByMajorInner {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'majorCode': json['majorCode'],
    };
}

export function StudentStatisticsResponseStudentsByMajorInnerToJSON(json: any): StudentStatisticsResponseStudentsByMajorInner {
    return StudentStatisticsResponseStudentsByMajorInnerToJSONTyped(json, false);
}

export function StudentStatisticsResponseStudentsByMajorInnerToJSONTyped(value?: StudentStatisticsResponseStudentsByMajorInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'majorCode': value['majorCode'],
    };
}

