/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentStatisticsResponseStudentsByFacultyInner
 */
export interface StudentStatisticsResponseStudentsByFacultyInner {
    /**
     * 
     * @type {number}
     * @memberof StudentStatisticsResponseStudentsByFacultyInner
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof StudentStatisticsResponseStudentsByFacultyInner
     */
    facultyCode: string;
}

/**
 * Check if a given object implements the StudentStatisticsResponseStudentsByFacultyInner interface.
 */
export function instanceOfStudentStatisticsResponseStudentsByFacultyInner(value: object): value is StudentStatisticsResponseStudentsByFacultyInner {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('facultyCode' in value) || value['facultyCode'] === undefined) return false;
    return true;
}

export function StudentStatisticsResponseStudentsByFacultyInnerFromJSON(json: any): StudentStatisticsResponseStudentsByFacultyInner {
    return StudentStatisticsResponseStudentsByFacultyInnerFromJSONTyped(json, false);
}

export function StudentStatisticsResponseStudentsByFacultyInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentStatisticsResponseStudentsByFacultyInner {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'facultyCode': json['facultyCode'],
    };
}

export function StudentStatisticsResponseStudentsByFacultyInnerToJSON(json: any): StudentStatisticsResponseStudentsByFacultyInner {
    return StudentStatisticsResponseStudentsByFacultyInnerToJSONTyped(json, false);
}

export function StudentStatisticsResponseStudentsByFacultyInnerToJSONTyped(value?: StudentStatisticsResponseStudentsByFacultyInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'facultyCode': value['facultyCode'],
    };
}

