/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentSearchResponseFilters
 */
export interface StudentSearchResponseFilters {
    /**
     * 
     * @type {number}
     * @memberof StudentSearchResponseFilters
     */
    studentStatusId?: number;
    /**
     * 
     * @type {string}
     * @memberof StudentSearchResponseFilters
     */
    section?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentSearchResponseFilters
     */
    majorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentSearchResponseFilters
     */
    facultyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentSearchResponseFilters
     */
    campusCode?: string;
}

/**
 * Check if a given object implements the StudentSearchResponseFilters interface.
 */
export function instanceOfStudentSearchResponseFilters(value: object): value is StudentSearchResponseFilters {
    return true;
}

export function StudentSearchResponseFiltersFromJSON(json: any): StudentSearchResponseFilters {
    return StudentSearchResponseFiltersFromJSONTyped(json, false);
}

export function StudentSearchResponseFiltersFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentSearchResponseFilters {
    if (json == null) {
        return json;
    }
    return {
        
        'studentStatusId': json['studentStatusId'] == null ? undefined : json['studentStatusId'],
        'section': json['section'] == null ? undefined : json['section'],
        'majorCode': json['majorCode'] == null ? undefined : json['majorCode'],
        'facultyCode': json['facultyCode'] == null ? undefined : json['facultyCode'],
        'campusCode': json['campusCode'] == null ? undefined : json['campusCode'],
    };
}

export function StudentSearchResponseFiltersToJSON(json: any): StudentSearchResponseFilters {
    return StudentSearchResponseFiltersToJSONTyped(json, false);
}

export function StudentSearchResponseFiltersToJSONTyped(value?: StudentSearchResponseFilters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studentStatusId': value['studentStatusId'],
        'section': value['section'],
        'majorCode': value['majorCode'],
        'facultyCode': value['facultyCode'],
        'campusCode': value['campusCode'],
    };
}

