/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudentResponse
 */
export interface StudentResponse {
    /**
     * 
     * @type {number}
     * @memberof StudentResponse
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    studentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    campusCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    facultyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    majorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    departmentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    section?: string;
    /**
     * 
     * @type {string}
     * @memberof StudentResponse
     */
    advisorCode?: string;
    /**
     * 
     * @type {number}
     * @memberof StudentResponse
     */
    studentStatusId?: number;
    /**
     * 
     * @type {Date}
     * @memberof StudentResponse
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof StudentResponse
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the StudentResponse interface.
 */
export function instanceOfStudentResponse(value: object): value is StudentResponse {
    return true;
}

export function StudentResponseFromJSON(json: any): StudentResponse {
    return StudentResponseFromJSONTyped(json, false);
}

export function StudentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'studentCode': json['studentCode'] == null ? undefined : json['studentCode'],
        'campusCode': json['campusCode'] == null ? undefined : json['campusCode'],
        'facultyCode': json['facultyCode'] == null ? undefined : json['facultyCode'],
        'majorCode': json['majorCode'] == null ? undefined : json['majorCode'],
        'departmentCode': json['departmentCode'] == null ? undefined : json['departmentCode'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'section': json['section'] == null ? undefined : json['section'],
        'advisorCode': json['advisorCode'] == null ? undefined : json['advisorCode'],
        'studentStatusId': json['studentStatusId'] == null ? undefined : json['studentStatusId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function StudentResponseToJSON(json: any): StudentResponse {
    return StudentResponseToJSONTyped(json, false);
}

export function StudentResponseToJSONTyped(value?: StudentResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'studentCode': value['studentCode'],
        'campusCode': value['campusCode'],
        'facultyCode': value['facultyCode'],
        'majorCode': value['majorCode'],
        'departmentCode': value['departmentCode'],
        'phone': value['phone'],
        'email': value['email'],
        'section': value['section'],
        'advisorCode': value['advisorCode'],
        'studentStatusId': value['studentStatusId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

