/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StudentStatisticsResponseStudentsByFacultyInner } from './StudentStatisticsResponseStudentsByFacultyInner';
import {
    StudentStatisticsResponseStudentsByFacultyInnerFromJSON,
    StudentStatisticsResponseStudentsByFacultyInnerFromJSONTyped,
    StudentStatisticsResponseStudentsByFacultyInnerToJSON,
    StudentStatisticsResponseStudentsByFacultyInnerToJSONTyped,
} from './StudentStatisticsResponseStudentsByFacultyInner';
import type { StudentStatisticsResponseStudentsByMajorInner } from './StudentStatisticsResponseStudentsByMajorInner';
import {
    StudentStatisticsResponseStudentsByMajorInnerFromJSON,
    StudentStatisticsResponseStudentsByMajorInnerFromJSONTyped,
    StudentStatisticsResponseStudentsByMajorInnerToJSON,
    StudentStatisticsResponseStudentsByMajorInnerToJSONTyped,
} from './StudentStatisticsResponseStudentsByMajorInner';
import type { StudentStatisticsResponseStudentsByCampusInner } from './StudentStatisticsResponseStudentsByCampusInner';
import {
    StudentStatisticsResponseStudentsByCampusInnerFromJSON,
    StudentStatisticsResponseStudentsByCampusInnerFromJSONTyped,
    StudentStatisticsResponseStudentsByCampusInnerToJSON,
    StudentStatisticsResponseStudentsByCampusInnerToJSONTyped,
} from './StudentStatisticsResponseStudentsByCampusInner';
import type { StudentStatisticsResponseStudentsByStatusInner } from './StudentStatisticsResponseStudentsByStatusInner';
import {
    StudentStatisticsResponseStudentsByStatusInnerFromJSON,
    StudentStatisticsResponseStudentsByStatusInnerFromJSONTyped,
    StudentStatisticsResponseStudentsByStatusInnerToJSON,
    StudentStatisticsResponseStudentsByStatusInnerToJSONTyped,
} from './StudentStatisticsResponseStudentsByStatusInner';

/**
 * 
 * @export
 * @interface StudentStatisticsResponse
 */
export interface StudentStatisticsResponse {
    /**
     * 
     * @type {number}
     * @memberof StudentStatisticsResponse
     */
    totalStudents: number;
    /**
     * 
     * @type {Array<StudentStatisticsResponseStudentsByCampusInner>}
     * @memberof StudentStatisticsResponse
     */
    studentsByCampus: Array<StudentStatisticsResponseStudentsByCampusInner>;
    /**
     * 
     * @type {Array<StudentStatisticsResponseStudentsByFacultyInner>}
     * @memberof StudentStatisticsResponse
     */
    studentsByFaculty: Array<StudentStatisticsResponseStudentsByFacultyInner>;
    /**
     * 
     * @type {Array<StudentStatisticsResponseStudentsByMajorInner>}
     * @memberof StudentStatisticsResponse
     */
    studentsByMajor: Array<StudentStatisticsResponseStudentsByMajorInner>;
    /**
     * 
     * @type {Array<StudentStatisticsResponseStudentsByStatusInner>}
     * @memberof StudentStatisticsResponse
     */
    studentsByStatus: Array<StudentStatisticsResponseStudentsByStatusInner>;
}

/**
 * Check if a given object implements the StudentStatisticsResponse interface.
 */
export function instanceOfStudentStatisticsResponse(value: object): value is StudentStatisticsResponse {
    if (!('totalStudents' in value) || value['totalStudents'] === undefined) return false;
    if (!('studentsByCampus' in value) || value['studentsByCampus'] === undefined) return false;
    if (!('studentsByFaculty' in value) || value['studentsByFaculty'] === undefined) return false;
    if (!('studentsByMajor' in value) || value['studentsByMajor'] === undefined) return false;
    if (!('studentsByStatus' in value) || value['studentsByStatus'] === undefined) return false;
    return true;
}

export function StudentStatisticsResponseFromJSON(json: any): StudentStatisticsResponse {
    return StudentStatisticsResponseFromJSONTyped(json, false);
}

export function StudentStatisticsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudentStatisticsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'totalStudents': json['totalStudents'],
        'studentsByCampus': ((json['studentsByCampus'] as Array<any>).map(StudentStatisticsResponseStudentsByCampusInnerFromJSON)),
        'studentsByFaculty': ((json['studentsByFaculty'] as Array<any>).map(StudentStatisticsResponseStudentsByFacultyInnerFromJSON)),
        'studentsByMajor': ((json['studentsByMajor'] as Array<any>).map(StudentStatisticsResponseStudentsByMajorInnerFromJSON)),
        'studentsByStatus': ((json['studentsByStatus'] as Array<any>).map(StudentStatisticsResponseStudentsByStatusInnerFromJSON)),
    };
}

export function StudentStatisticsResponseToJSON(json: any): StudentStatisticsResponse {
    return StudentStatisticsResponseToJSONTyped(json, false);
}

export function StudentStatisticsResponseToJSONTyped(value?: StudentStatisticsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'totalStudents': value['totalStudents'],
        'studentsByCampus': ((value['studentsByCampus'] as Array<any>).map(StudentStatisticsResponseStudentsByCampusInnerToJSON)),
        'studentsByFaculty': ((value['studentsByFaculty'] as Array<any>).map(StudentStatisticsResponseStudentsByFacultyInnerToJSON)),
        'studentsByMajor': ((value['studentsByMajor'] as Array<any>).map(StudentStatisticsResponseStudentsByMajorInnerToJSON)),
        'studentsByStatus': ((value['studentsByStatus'] as Array<any>).map(StudentStatisticsResponseStudentsByStatusInnerToJSON)),
    };
}

