/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserRequest
 */
export interface UpdateUserRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    passwordHashed?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    roleCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    campusCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    facultyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    majorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    departmentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    advisorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the UpdateUserRequest interface.
 */
export function instanceOfUpdateUserRequest(value: object): value is UpdateUserRequest {
    return true;
}

export function UpdateUserRequestFromJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestFromJSONTyped(json, false);
}

export function UpdateUserRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'] == null ? undefined : json['username'],
        'passwordHashed': json['passwordHashed'] == null ? undefined : json['passwordHashed'],
        'roleCode': json['roleCode'] == null ? undefined : json['roleCode'],
        'campusCode': json['campusCode'] == null ? undefined : json['campusCode'],
        'facultyCode': json['facultyCode'] == null ? undefined : json['facultyCode'],
        'majorCode': json['majorCode'] == null ? undefined : json['majorCode'],
        'departmentCode': json['departmentCode'] == null ? undefined : json['departmentCode'],
        'advisorCode': json['advisorCode'] == null ? undefined : json['advisorCode'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function UpdateUserRequestToJSON(json: any): UpdateUserRequest {
    return UpdateUserRequestToJSONTyped(json, false);
}

export function UpdateUserRequestToJSONTyped(value?: UpdateUserRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'passwordHashed': value['passwordHashed'],
        'roleCode': value['roleCode'],
        'campusCode': value['campusCode'],
        'facultyCode': value['facultyCode'],
        'majorCode': value['majorCode'],
        'departmentCode': value['departmentCode'],
        'advisorCode': value['advisorCode'],
        'phone': value['phone'],
        'email': value['email'],
    };
}

