/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateUserResponse
 */
export interface UpdateUserResponse {
    /**
     * 
     * @type {number}
     * @memberof UpdateUserResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateUserResponse
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the UpdateUserResponse interface.
 */
export function instanceOfUpdateUserResponse(value: object): value is UpdateUserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UpdateUserResponseFromJSON(json: any): UpdateUserResponse {
    return UpdateUserResponseFromJSONTyped(json, false);
}

export function UpdateUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'message': json['message'],
        'success': json['success'],
    };
}

export function UpdateUserResponseToJSON(json: any): UpdateUserResponse {
    return UpdateUserResponseToJSONTyped(json, false);
}

export function UpdateUserResponseToJSONTyped(value?: UpdateUserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'message': value['message'],
        'success': value['success'],
    };
}

