/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateStudentRequest
 */
export interface UpdateStudentRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    studentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    campusCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    facultyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    majorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    departmentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    section?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateStudentRequest
     */
    advisorCode?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateStudentRequest
     */
    studentStatusId?: number;
}

/**
 * Check if a given object implements the UpdateStudentRequest interface.
 */
export function instanceOfUpdateStudentRequest(value: object): value is UpdateStudentRequest {
    return true;
}

export function UpdateStudentRequestFromJSON(json: any): UpdateStudentRequest {
    return UpdateStudentRequestFromJSONTyped(json, false);
}

export function UpdateStudentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateStudentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'studentCode': json['studentCode'] == null ? undefined : json['studentCode'],
        'campusCode': json['campusCode'] == null ? undefined : json['campusCode'],
        'facultyCode': json['facultyCode'] == null ? undefined : json['facultyCode'],
        'majorCode': json['majorCode'] == null ? undefined : json['majorCode'],
        'departmentCode': json['departmentCode'] == null ? undefined : json['departmentCode'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'section': json['section'] == null ? undefined : json['section'],
        'advisorCode': json['advisorCode'] == null ? undefined : json['advisorCode'],
        'studentStatusId': json['studentStatusId'] == null ? undefined : json['studentStatusId'],
    };
}

export function UpdateStudentRequestToJSON(json: any): UpdateStudentRequest {
    return UpdateStudentRequestToJSONTyped(json, false);
}

export function UpdateStudentRequestToJSONTyped(value?: UpdateStudentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'studentCode': value['studentCode'],
        'campusCode': value['campusCode'],
        'facultyCode': value['facultyCode'],
        'majorCode': value['majorCode'],
        'departmentCode': value['departmentCode'],
        'phone': value['phone'],
        'email': value['email'],
        'section': value['section'],
        'advisorCode': value['advisorCode'],
        'studentStatusId': value['studentStatusId'],
    };
}

