/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegisterRequest
 */
export interface UserRegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    roleCode: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    campusCode: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    facultyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    majorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    departmentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    advisorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the UserRegisterRequest interface.
 */
export function instanceOfUserRegisterRequest(value: object): value is UserRegisterRequest {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('roleCode' in value) || value['roleCode'] === undefined) return false;
    if (!('campusCode' in value) || value['campusCode'] === undefined) return false;
    return true;
}

export function UserRegisterRequestFromJSON(json: any): UserRegisterRequest {
    return UserRegisterRequestFromJSONTyped(json, false);
}

export function UserRegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
        'roleCode': json['roleCode'],
        'campusCode': json['campusCode'],
        'facultyCode': json['facultyCode'] == null ? undefined : json['facultyCode'],
        'majorCode': json['majorCode'] == null ? undefined : json['majorCode'],
        'departmentCode': json['departmentCode'] == null ? undefined : json['departmentCode'],
        'advisorCode': json['advisorCode'] == null ? undefined : json['advisorCode'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function UserRegisterRequestToJSON(json: any): UserRegisterRequest {
    return UserRegisterRequestToJSONTyped(json, false);
}

export function UserRegisterRequestToJSONTyped(value?: UserRegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
        'roleCode': value['roleCode'],
        'campusCode': value['campusCode'],
        'facultyCode': value['facultyCode'],
        'majorCode': value['majorCode'],
        'departmentCode': value['departmentCode'],
        'advisorCode': value['advisorCode'],
        'phone': value['phone'],
        'email': value['email'],
    };
}

