/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserLoginResponse
 */
export interface UserLoginResponse {
    /**
     * 
     * @type {number}
     * @memberof UserLoginResponse
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    roleCode: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    campusCode: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    facultyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    majorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    departmentCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    advisorCode?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    refreshToken: string;
    /**
     * 
     * @type {number}
     * @memberof UserLoginResponse
     */
    expiresIn: number;
    /**
     * 
     * @type {string}
     * @memberof UserLoginResponse
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof UserLoginResponse
     */
    success: boolean;
}

/**
 * Check if a given object implements the UserLoginResponse interface.
 */
export function instanceOfUserLoginResponse(value: object): value is UserLoginResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('roleCode' in value) || value['roleCode'] === undefined) return false;
    if (!('campusCode' in value) || value['campusCode'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('expiresIn' in value) || value['expiresIn'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function UserLoginResponseFromJSON(json: any): UserLoginResponse {
    return UserLoginResponseFromJSONTyped(json, false);
}

export function UserLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'username': json['username'],
        'roleCode': json['roleCode'],
        'campusCode': json['campusCode'],
        'facultyCode': json['facultyCode'] == null ? undefined : json['facultyCode'],
        'majorCode': json['majorCode'] == null ? undefined : json['majorCode'],
        'departmentCode': json['departmentCode'] == null ? undefined : json['departmentCode'],
        'advisorCode': json['advisorCode'] == null ? undefined : json['advisorCode'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'email': json['email'] == null ? undefined : json['email'],
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'expiresIn': json['expiresIn'],
        'message': json['message'],
        'success': json['success'],
    };
}

export function UserLoginResponseToJSON(json: any): UserLoginResponse {
    return UserLoginResponseToJSONTyped(json, false);
}

export function UserLoginResponseToJSONTyped(value?: UserLoginResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'username': value['username'],
        'roleCode': value['roleCode'],
        'campusCode': value['campusCode'],
        'facultyCode': value['facultyCode'],
        'majorCode': value['majorCode'],
        'departmentCode': value['departmentCode'],
        'advisorCode': value['advisorCode'],
        'phone': value['phone'],
        'email': value['email'],
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'expiresIn': value['expiresIn'],
        'message': value['message'],
        'success': value['success'],
    };
}

