/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserChangePasswordRequest
 */
export interface UserChangePasswordRequest {
    /**
     * 
     * @type {string}
     * @memberof UserChangePasswordRequest
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof UserChangePasswordRequest
     */
    oldPassword: string;
}

/**
 * Check if a given object implements the UserChangePasswordRequest interface.
 */
export function instanceOfUserChangePasswordRequest(value: object): value is UserChangePasswordRequest {
    if (!('newPassword' in value) || value['newPassword'] === undefined) return false;
    if (!('oldPassword' in value) || value['oldPassword'] === undefined) return false;
    return true;
}

export function UserChangePasswordRequestFromJSON(json: any): UserChangePasswordRequest {
    return UserChangePasswordRequestFromJSONTyped(json, false);
}

export function UserChangePasswordRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserChangePasswordRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['newPassword'],
        'oldPassword': json['oldPassword'],
    };
}

export function UserChangePasswordRequestToJSON(json: any): UserChangePasswordRequest {
    return UserChangePasswordRequestToJSONTyped(json, false);
}

export function UserChangePasswordRequestToJSONTyped(value?: UserChangePasswordRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'newPassword': value['newPassword'],
        'oldPassword': value['oldPassword'],
    };
}

