/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DashboardRequestListResponse,
  DashboardSummaryItem,
} from '../models/index';
import {
    DashboardRequestListResponseFromJSON,
    DashboardRequestListResponseToJSON,
    DashboardSummaryItemFromJSON,
    DashboardSummaryItemToJSON,
} from '../models/index';

export interface GetRequestsRequest {
    page?: number;
    pageSize?: number;
    month?: number;
    term?: string;
    year?: number;
    requestType?: string;
}

export interface GetSummaryRequest {
    month?: number;
    term?: string;
    year?: number;
    requestType?: string;
}

/**
 * DashboardApi - interface
 * 
 * @export
 * @interface DashboardApiInterface
 */
export interface DashboardApiInterface {
    /**
     * Dashboard request list with filters and pagination
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {number} [month] 
     * @param {string} [term] 
     * @param {number} [year] 
     * @param {string} [requestType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getRequestsRaw(requestParameters: GetRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DashboardRequestListResponse>>;

    /**
     * Dashboard request list with filters and pagination
     */
    getRequests(requestParameters: GetRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DashboardRequestListResponse>;

    /**
     * Dashboard summary counts by status
     * @param {number} [month] 
     * @param {string} [term] 
     * @param {number} [year] 
     * @param {string} [requestType] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DashboardApiInterface
     */
    getSummaryRaw(requestParameters: GetSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DashboardSummaryItem>>>;

    /**
     * Dashboard summary counts by status
     */
    getSummary(requestParameters: GetSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DashboardSummaryItem>>;

}

/**
 * 
 */
export class DashboardApi extends runtime.BaseAPI implements DashboardApiInterface {

    /**
     * Dashboard request list with filters and pagination
     */
    async getRequestsRaw(requestParameters: GetRequestsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DashboardRequestListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['term'] != null) {
            queryParameters['term'] = requestParameters['term'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        if (requestParameters['requestType'] != null) {
            queryParameters['requestType'] = requestParameters['requestType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/dashboard/requests`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DashboardRequestListResponseFromJSON(jsonValue));
    }

    /**
     * Dashboard request list with filters and pagination
     */
    async getRequests(requestParameters: GetRequestsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DashboardRequestListResponse> {
        const response = await this.getRequestsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Dashboard summary counts by status
     */
    async getSummaryRaw(requestParameters: GetSummaryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DashboardSummaryItem>>> {
        const queryParameters: any = {};

        if (requestParameters['month'] != null) {
            queryParameters['month'] = requestParameters['month'];
        }

        if (requestParameters['term'] != null) {
            queryParameters['term'] = requestParameters['term'];
        }

        if (requestParameters['year'] != null) {
            queryParameters['year'] = requestParameters['year'];
        }

        if (requestParameters['requestType'] != null) {
            queryParameters['requestType'] = requestParameters['requestType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/dashboard/summary`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DashboardSummaryItemFromJSON));
    }

    /**
     * Dashboard summary counts by status
     */
    async getSummary(requestParameters: GetSummaryRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DashboardSummaryItem>> {
        const response = await this.getSummaryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
