/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MasterValueDetailResponse,
  MasterValueHeaderResponse,
  SaveMasterValueDetailRequest,
  SaveMasterValueHeaderRequest,
} from '../models/index';
import {
    MasterValueDetailResponseFromJSON,
    MasterValueDetailResponseToJSON,
    MasterValueHeaderResponseFromJSON,
    MasterValueHeaderResponseToJSON,
    SaveMasterValueDetailRequestFromJSON,
    SaveMasterValueDetailRequestToJSON,
    SaveMasterValueHeaderRequestFromJSON,
    SaveMasterValueHeaderRequestToJSON,
} from '../models/index';

export interface FindMasterValueDetailGetRequest {
    masterValueDetailCode: string;
}

export interface FindMasterValueDetailsByHeaderGetRequest {
    headerCode: string;
}

export interface FindMasterValueHeaderGetRequest {
    masterValueHeaderCode: string;
}

export interface SaveMasterValueDetailPostRequest {
    saveMasterValueDetailRequest: SaveMasterValueDetailRequest;
}

export interface SaveMasterValueHeaderPostRequest {
    saveMasterValueHeaderRequest: SaveMasterValueHeaderRequest;
}

/**
 * IRAM06MasterValueApi - interface
 * 
 * @export
 * @interface IRAM06MasterValueApiInterface
 */
export interface IRAM06MasterValueApiInterface {
    /**
     * ค้นหาข้อมูล Master Value Detail ตาม code
     * @param {string} masterValueDetailCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueApiInterface
     */
    findMasterValueDetailGetRaw(requestParameters: FindMasterValueDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueDetailResponse>>;

    /**
     * ค้นหาข้อมูล Master Value Detail ตาม code
     */
    findMasterValueDetailGet(requestParameters: FindMasterValueDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueDetailResponse>;

    /**
     * ค้นหาข้อมูล Master Value Detail ตาม header code เรียงตาม sequence
     * @param {string} headerCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueApiInterface
     */
    findMasterValueDetailsByHeaderGetRaw(requestParameters: FindMasterValueDetailsByHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MasterValueDetailResponse>>>;

    /**
     * ค้นหาข้อมูล Master Value Detail ตาม header code เรียงตาม sequence
     */
    findMasterValueDetailsByHeaderGet(requestParameters: FindMasterValueDetailsByHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MasterValueDetailResponse>>;

    /**
     * ค้นหาข้อมูล Master Value Header ตาม code
     * @param {string} masterValueHeaderCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueApiInterface
     */
    findMasterValueHeaderGetRaw(requestParameters: FindMasterValueHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueHeaderResponse>>;

    /**
     * ค้นหาข้อมูล Master Value Header ตาม code
     */
    findMasterValueHeaderGet(requestParameters: FindMasterValueHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueHeaderResponse>;

    /**
     * บันทึกข้อมูล Master Value Detail
     * @param {SaveMasterValueDetailRequest} saveMasterValueDetailRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueApiInterface
     */
    saveMasterValueDetailPostRaw(requestParameters: SaveMasterValueDetailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueDetailResponse>>;

    /**
     * บันทึกข้อมูล Master Value Detail
     */
    saveMasterValueDetailPost(requestParameters: SaveMasterValueDetailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueDetailResponse>;

    /**
     * บันทึกข้อมูล Master Value Header
     * @param {SaveMasterValueHeaderRequest} saveMasterValueHeaderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueApiInterface
     */
    saveMasterValueHeaderPostRaw(requestParameters: SaveMasterValueHeaderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueHeaderResponse>>;

    /**
     * บันทึกข้อมูล Master Value Header
     */
    saveMasterValueHeaderPost(requestParameters: SaveMasterValueHeaderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueHeaderResponse>;

}

/**
 * 
 */
export class IRAM06MasterValueApi extends runtime.BaseAPI implements IRAM06MasterValueApiInterface {

    /**
     * ค้นหาข้อมูล Master Value Detail ตาม code
     */
    async findMasterValueDetailGetRaw(requestParameters: FindMasterValueDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueDetailResponse>> {
        if (requestParameters['masterValueDetailCode'] == null) {
            throw new runtime.RequiredError(
                'masterValueDetailCode',
                'Required parameter "masterValueDetailCode" was null or undefined when calling findMasterValueDetailGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['masterValueDetailCode'] != null) {
            queryParameters['master-value-detail-code'] = requestParameters['masterValueDetailCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/iram06/find-master-value-detail-get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MasterValueDetailResponseFromJSON(jsonValue));
    }

    /**
     * ค้นหาข้อมูล Master Value Detail ตาม code
     */
    async findMasterValueDetailGet(requestParameters: FindMasterValueDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueDetailResponse> {
        const response = await this.findMasterValueDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ค้นหาข้อมูล Master Value Detail ตาม header code เรียงตาม sequence
     */
    async findMasterValueDetailsByHeaderGetRaw(requestParameters: FindMasterValueDetailsByHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MasterValueDetailResponse>>> {
        if (requestParameters['headerCode'] == null) {
            throw new runtime.RequiredError(
                'headerCode',
                'Required parameter "headerCode" was null or undefined when calling findMasterValueDetailsByHeaderGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['headerCode'] != null) {
            queryParameters['header-code'] = requestParameters['headerCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/iram06/find-master-value-details-by-header-get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MasterValueDetailResponseFromJSON));
    }

    /**
     * ค้นหาข้อมูล Master Value Detail ตาม header code เรียงตาม sequence
     */
    async findMasterValueDetailsByHeaderGet(requestParameters: FindMasterValueDetailsByHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MasterValueDetailResponse>> {
        const response = await this.findMasterValueDetailsByHeaderGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ค้นหาข้อมูล Master Value Header ตาม code
     */
    async findMasterValueHeaderGetRaw(requestParameters: FindMasterValueHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueHeaderResponse>> {
        if (requestParameters['masterValueHeaderCode'] == null) {
            throw new runtime.RequiredError(
                'masterValueHeaderCode',
                'Required parameter "masterValueHeaderCode" was null or undefined when calling findMasterValueHeaderGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['masterValueHeaderCode'] != null) {
            queryParameters['master-value-header-code'] = requestParameters['masterValueHeaderCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/iram06/find-master-value-header-get`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MasterValueHeaderResponseFromJSON(jsonValue));
    }

    /**
     * ค้นหาข้อมูล Master Value Header ตาม code
     */
    async findMasterValueHeaderGet(requestParameters: FindMasterValueHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueHeaderResponse> {
        const response = await this.findMasterValueHeaderGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * บันทึกข้อมูล Master Value Detail
     */
    async saveMasterValueDetailPostRaw(requestParameters: SaveMasterValueDetailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueDetailResponse>> {
        if (requestParameters['saveMasterValueDetailRequest'] == null) {
            throw new runtime.RequiredError(
                'saveMasterValueDetailRequest',
                'Required parameter "saveMasterValueDetailRequest" was null or undefined when calling saveMasterValueDetailPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/iram06/save-master-value-detail-post`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveMasterValueDetailRequestToJSON(requestParameters['saveMasterValueDetailRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MasterValueDetailResponseFromJSON(jsonValue));
    }

    /**
     * บันทึกข้อมูล Master Value Detail
     */
    async saveMasterValueDetailPost(requestParameters: SaveMasterValueDetailPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueDetailResponse> {
        const response = await this.saveMasterValueDetailPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * บันทึกข้อมูล Master Value Header
     */
    async saveMasterValueHeaderPostRaw(requestParameters: SaveMasterValueHeaderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueHeaderResponse>> {
        if (requestParameters['saveMasterValueHeaderRequest'] == null) {
            throw new runtime.RequiredError(
                'saveMasterValueHeaderRequest',
                'Required parameter "saveMasterValueHeaderRequest" was null or undefined when calling saveMasterValueHeaderPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/iram06/save-master-value-header-post`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveMasterValueHeaderRequestToJSON(requestParameters['saveMasterValueHeaderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MasterValueHeaderResponseFromJSON(jsonValue));
    }

    /**
     * บันทึกข้อมูล Master Value Header
     */
    async saveMasterValueHeaderPost(requestParameters: SaveMasterValueHeaderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueHeaderResponse> {
        const response = await this.saveMasterValueHeaderPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
