/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MasterValueDetailResponse,
  MasterValueHeaderResponse,
  SaveMasterValueDetailPostRequest,
  SaveMasterValueHeaderPostRequest,
} from '../models/index';
import {
    MasterValueDetailResponseFromJSON,
    MasterValueDetailResponseToJSON,
    MasterValueHeaderResponseFromJSON,
    MasterValueHeaderResponseToJSON,
    SaveMasterValueDetailPostRequestFromJSON,
    SaveMasterValueDetailPostRequestToJSON,
    SaveMasterValueHeaderPostRequestFromJSON,
    SaveMasterValueHeaderPostRequestToJSON,
} from '../models/index';

export interface FindMasterValueDetailGetRequest {
    masterValueDetailCode?: string;
    masterValueHeaderId?: number;
}

export interface FindMasterValueDetailsByHeaderGetRequest {
    masterValueHeaderId: number;
}

export interface FindMasterValueHeaderGetRequest {
    masterValueCode?: string;
}

export interface SaveMasterValueDetailPostOperationRequest {
    saveMasterValueDetailPostRequest: SaveMasterValueDetailPostRequest;
}

export interface SaveMasterValueHeaderPostOperationRequest {
    saveMasterValueHeaderPostRequest: SaveMasterValueHeaderPostRequest;
}

/**
 * IRAM06MasterValueManagementApi - interface
 * 
 * @export
 * @interface IRAM06MasterValueManagementApiInterface
 */
export interface IRAM06MasterValueManagementApiInterface {
    /**
     * 
     * @param {string} [masterValueDetailCode] 
     * @param {number} [masterValueHeaderId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueManagementApiInterface
     */
    findMasterValueDetailGetRaw(requestParameters: FindMasterValueDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueDetailResponse>>;

    /**
     */
    findMasterValueDetailGet(requestParameters: FindMasterValueDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueDetailResponse>;

    /**
     * 
     * @param {number} masterValueHeaderId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueManagementApiInterface
     */
    findMasterValueDetailsByHeaderGetRaw(requestParameters: FindMasterValueDetailsByHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MasterValueDetailResponse>>>;

    /**
     */
    findMasterValueDetailsByHeaderGet(requestParameters: FindMasterValueDetailsByHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MasterValueDetailResponse>>;

    /**
     * 
     * @param {string} [masterValueCode] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueManagementApiInterface
     */
    findMasterValueHeaderGetRaw(requestParameters: FindMasterValueHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueHeaderResponse>>;

    /**
     */
    findMasterValueHeaderGet(requestParameters: FindMasterValueHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueHeaderResponse>;

    /**
     * 
     * @param {SaveMasterValueDetailPostRequest} saveMasterValueDetailPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueManagementApiInterface
     */
    saveMasterValueDetailPostRaw(requestParameters: SaveMasterValueDetailPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueDetailResponse>>;

    /**
     */
    saveMasterValueDetailPost(requestParameters: SaveMasterValueDetailPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueDetailResponse>;

    /**
     * 
     * @param {SaveMasterValueHeaderPostRequest} saveMasterValueHeaderPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRAM06MasterValueManagementApiInterface
     */
    saveMasterValueHeaderPostRaw(requestParameters: SaveMasterValueHeaderPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueHeaderResponse>>;

    /**
     */
    saveMasterValueHeaderPost(requestParameters: SaveMasterValueHeaderPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueHeaderResponse>;

}

/**
 * 
 */
export class IRAM06MasterValueManagementApi extends runtime.BaseAPI implements IRAM06MasterValueManagementApiInterface {

    /**
     */
    async findMasterValueDetailGetRaw(requestParameters: FindMasterValueDetailGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueDetailResponse>> {
        const queryParameters: any = {};

        if (requestParameters['masterValueDetailCode'] != null) {
            queryParameters['masterValueDetailCode'] = requestParameters['masterValueDetailCode'];
        }

        if (requestParameters['masterValueHeaderId'] != null) {
            queryParameters['masterValueHeaderId'] = requestParameters['masterValueHeaderId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/iram06/find-master-value-detail`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MasterValueDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async findMasterValueDetailGet(requestParameters: FindMasterValueDetailGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueDetailResponse> {
        const response = await this.findMasterValueDetailGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async findMasterValueDetailsByHeaderGetRaw(requestParameters: FindMasterValueDetailsByHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<MasterValueDetailResponse>>> {
        if (requestParameters['masterValueHeaderId'] == null) {
            throw new runtime.RequiredError(
                'masterValueHeaderId',
                'Required parameter "masterValueHeaderId" was null or undefined when calling findMasterValueDetailsByHeaderGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['masterValueHeaderId'] != null) {
            queryParameters['masterValueHeaderId'] = requestParameters['masterValueHeaderId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/iram06/find-master-value-details-by-header`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(MasterValueDetailResponseFromJSON));
    }

    /**
     */
    async findMasterValueDetailsByHeaderGet(requestParameters: FindMasterValueDetailsByHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<MasterValueDetailResponse>> {
        const response = await this.findMasterValueDetailsByHeaderGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async findMasterValueHeaderGetRaw(requestParameters: FindMasterValueHeaderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueHeaderResponse>> {
        const queryParameters: any = {};

        if (requestParameters['masterValueCode'] != null) {
            queryParameters['masterValueCode'] = requestParameters['masterValueCode'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/iram06/find-master-value-header`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MasterValueHeaderResponseFromJSON(jsonValue));
    }

    /**
     */
    async findMasterValueHeaderGet(requestParameters: FindMasterValueHeaderGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueHeaderResponse> {
        const response = await this.findMasterValueHeaderGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async saveMasterValueDetailPostRaw(requestParameters: SaveMasterValueDetailPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueDetailResponse>> {
        if (requestParameters['saveMasterValueDetailPostRequest'] == null) {
            throw new runtime.RequiredError(
                'saveMasterValueDetailPostRequest',
                'Required parameter "saveMasterValueDetailPostRequest" was null or undefined when calling saveMasterValueDetailPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/iram06/save-master-value-detail`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveMasterValueDetailPostRequestToJSON(requestParameters['saveMasterValueDetailPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MasterValueDetailResponseFromJSON(jsonValue));
    }

    /**
     */
    async saveMasterValueDetailPost(requestParameters: SaveMasterValueDetailPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueDetailResponse> {
        const response = await this.saveMasterValueDetailPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async saveMasterValueHeaderPostRaw(requestParameters: SaveMasterValueHeaderPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MasterValueHeaderResponse>> {
        if (requestParameters['saveMasterValueHeaderPostRequest'] == null) {
            throw new runtime.RequiredError(
                'saveMasterValueHeaderPostRequest',
                'Required parameter "saveMasterValueHeaderPostRequest" was null or undefined when calling saveMasterValueHeaderPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/iram06/save-master-value-header`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SaveMasterValueHeaderPostRequestToJSON(requestParameters['saveMasterValueHeaderPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MasterValueHeaderResponseFromJSON(jsonValue));
    }

    /**
     */
    async saveMasterValueHeaderPost(requestParameters: SaveMasterValueHeaderPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MasterValueHeaderResponse> {
        const response = await this.saveMasterValueHeaderPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
