/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePostponeTuitionRequestPostRequest,
} from '../models/index';
import {
    CreatePostponeTuitionRequestPostRequestFromJSON,
    CreatePostponeTuitionRequestPostRequestToJSON,
} from '../models/index';

export interface CreatePostponeTuitionRequestPostOperationRequest {
    createPostponeTuitionRequestPostRequest: CreatePostponeTuitionRequestPostRequest;
}

export interface GetPostponeTuitionFeePdfRequest {
    uuid: string;
}

/**
 * Irst07PostponeTuitionFeePaymentRequestApi - interface
 * 
 * @export
 * @interface Irst07PostponeTuitionFeePaymentRequestApiInterface
 */
export interface Irst07PostponeTuitionFeePaymentRequestApiInterface {
    /**
     * 
     * @param {CreatePostponeTuitionRequestPostRequest} createPostponeTuitionRequestPostRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Irst07PostponeTuitionFeePaymentRequestApiInterface
     */
    createPostponeTuitionRequestPostRaw(requestParameters: CreatePostponeTuitionRequestPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     */
    createPostponeTuitionRequestPost(requestParameters: CreatePostponeTuitionRequestPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof Irst07PostponeTuitionFeePaymentRequestApiInterface
     */
    getPostponeTuitionFeePdfRaw(requestParameters: GetPostponeTuitionFeePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>>;

    /**
     */
    getPostponeTuitionFeePdf(requestParameters: GetPostponeTuitionFeePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob>;

}

/**
 * 
 */
export class Irst07PostponeTuitionFeePaymentRequestApi extends runtime.BaseAPI implements Irst07PostponeTuitionFeePaymentRequestApiInterface {

    /**
     */
    async createPostponeTuitionRequestPostRaw(requestParameters: CreatePostponeTuitionRequestPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['createPostponeTuitionRequestPostRequest'] == null) {
            throw new runtime.RequiredError(
                'createPostponeTuitionRequestPostRequest',
                'Required parameter "createPostponeTuitionRequestPostRequest" was null or undefined when calling createPostponeTuitionRequestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/irst07/create-request-post`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePostponeTuitionRequestPostRequestToJSON(requestParameters['createPostponeTuitionRequestPostRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createPostponeTuitionRequestPost(requestParameters: CreatePostponeTuitionRequestPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createPostponeTuitionRequestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getPostponeTuitionFeePdfRaw(requestParameters: GetPostponeTuitionFeePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getPostponeTuitionFeePdf().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Accept'] = 'application/pdf';

        let urlPath = `/irst07/pdf/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     */
    async getPostponeTuitionFeePdf(requestParameters: GetPostponeTuitionFeePdfRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.getPostponeTuitionFeePdfRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
