/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PostponeTuitionFee,
} from '../models/index';
import {
    PostponeTuitionFeeFromJSON,
    PostponeTuitionFeeToJSON,
} from '../models/index';

export interface CreatePostponeTuitionRequestPostRequest {
    postponeTuitionFee: PostponeTuitionFee;
}

/**
 * IRST07PostponeTuitionFeePaymentRequestApi - interface
 * 
 * @export
 * @interface IRST07PostponeTuitionFeePaymentRequestApiInterface
 */
export interface IRST07PostponeTuitionFeePaymentRequestApiInterface {
    /**
     * 
     * @param {PostponeTuitionFee} postponeTuitionFee 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRST07PostponeTuitionFeePaymentRequestApiInterface
     */
    createPostponeTuitionRequestPostRaw(requestParameters: CreatePostponeTuitionRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     */
    createPostponeTuitionRequestPost(requestParameters: CreatePostponeTuitionRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class IRST07PostponeTuitionFeePaymentRequestApi extends runtime.BaseAPI implements IRST07PostponeTuitionFeePaymentRequestApiInterface {

    /**
     */
    async createPostponeTuitionRequestPostRaw(requestParameters: CreatePostponeTuitionRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['postponeTuitionFee'] == null) {
            throw new runtime.RequiredError(
                'postponeTuitionFee',
                'Required parameter "postponeTuitionFee" was null or undefined when calling createPostponeTuitionRequestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/irst07/create-request-post`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostponeTuitionFeeToJSON(requestParameters['postponeTuitionFee']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createPostponeTuitionRequestPost(requestParameters: CreatePostponeTuitionRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createPostponeTuitionRequestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
