/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GeneralRequestRequest,
} from '../models/index';
import {
    GeneralRequestRequestFromJSON,
    GeneralRequestRequestToJSON,
} from '../models/index';

export interface CreateRequestPostRequest {
    generalRequestRequest: GeneralRequestRequest;
}

/**
 * IRST05GeneralRequestApi - interface
 * 
 * @export
 * @interface IRST05GeneralRequestApiInterface
 */
export interface IRST05GeneralRequestApiInterface {
    /**
     * 
     * @param {GeneralRequestRequest} generalRequestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IRST05GeneralRequestApiInterface
     */
    createRequestPostRaw(requestParameters: CreateRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>>;

    /**
     */
    createRequestPost(requestParameters: CreateRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any>;

}

/**
 * 
 */
export class IRST05GeneralRequestApi extends runtime.BaseAPI implements IRST05GeneralRequestApiInterface {

    /**
     */
    async createRequestPostRaw(requestParameters: CreateRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        if (requestParameters['generalRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'generalRequestRequest',
                'Required parameter "generalRequestRequest" was null or undefined when calling createRequestPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/irst05/create-request-post`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GeneralRequestRequestToJSON(requestParameters['generalRequestRequest']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     */
    async createRequestPost(requestParameters: CreateRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.createRequestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
