/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetRequestTypesResponse,
  RequestTypeResponse,
} from '../models/index';
import {
    GetRequestTypesResponseFromJSON,
    GetRequestTypesResponseToJSON,
    RequestTypeResponseFromJSON,
    RequestTypeResponseToJSON,
} from '../models/index';

export interface GetRequestTypeByUuidRequest {
    uuid: string;
}

export interface GetRequestTypesRequest {
    page?: number;
    pageSize?: number;
    search?: string;
    status?: string;
}

/**
 * RequestTypeManagementApi - interface
 * 
 * @export
 * @interface RequestTypeManagementApiInterface
 */
export interface RequestTypeManagementApiInterface {
    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestTypeManagementApiInterface
     */
    getRequestTypeByUuidRaw(requestParameters: GetRequestTypeByUuidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestTypeResponse>>;

    /**
     */
    getRequestTypeByUuid(requestParameters: GetRequestTypeByUuidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestTypeResponse>;

    /**
     * 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {string} [search] 
     * @param {string} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RequestTypeManagementApiInterface
     */
    getRequestTypesRaw(requestParameters: GetRequestTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRequestTypesResponse>>;

    /**
     */
    getRequestTypes(requestParameters: GetRequestTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRequestTypesResponse>;

}

/**
 * 
 */
export class RequestTypeManagementApi extends runtime.BaseAPI implements RequestTypeManagementApiInterface {

    /**
     */
    async getRequestTypeByUuidRaw(requestParameters: GetRequestTypeByUuidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RequestTypeResponse>> {
        if (requestParameters['uuid'] == null) {
            throw new runtime.RequiredError(
                'uuid',
                'Required parameter "uuid" was null or undefined when calling getRequestTypeByUuid().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/request-types/{uuid}`;
        urlPath = urlPath.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters['uuid'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RequestTypeResponseFromJSON(jsonValue));
    }

    /**
     */
    async getRequestTypeByUuid(requestParameters: GetRequestTypeByUuidRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RequestTypeResponse> {
        const response = await this.getRequestTypeByUuidRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRequestTypesRaw(requestParameters: GetRequestTypesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetRequestTypesResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/request-types`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetRequestTypesResponseFromJSON(jsonValue));
    }

    /**
     */
    async getRequestTypes(requestParameters: GetRequestTypesRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetRequestTypesResponse> {
        const response = await this.getRequestTypesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
