/* tslint:disable */
/* eslint-disable */
/**
 * IRequest Api Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CheckUsernameExists200Response,
  CreateStudentRequest,
  CreateStudentResponse,
  DeleteUser200Response,
  ExportStudentsData200Response,
  ImportStudentsData200Response,
  ImportStudentsDataRequest,
  StudentResponse,
  StudentSearchRequest,
  StudentSearchResponse,
  StudentStatisticsResponse,
  UpdateStudentRequest,
  UpdateStudentResponse,
} from '../models/index';
import {
    CheckUsernameExists200ResponseFromJSON,
    CheckUsernameExists200ResponseToJSON,
    CreateStudentRequestFromJSON,
    CreateStudentRequestToJSON,
    CreateStudentResponseFromJSON,
    CreateStudentResponseToJSON,
    DeleteUser200ResponseFromJSON,
    DeleteUser200ResponseToJSON,
    ExportStudentsData200ResponseFromJSON,
    ExportStudentsData200ResponseToJSON,
    ImportStudentsData200ResponseFromJSON,
    ImportStudentsData200ResponseToJSON,
    ImportStudentsDataRequestFromJSON,
    ImportStudentsDataRequestToJSON,
    StudentResponseFromJSON,
    StudentResponseToJSON,
    StudentSearchRequestFromJSON,
    StudentSearchRequestToJSON,
    StudentSearchResponseFromJSON,
    StudentSearchResponseToJSON,
    StudentStatisticsResponseFromJSON,
    StudentStatisticsResponseToJSON,
    UpdateStudentRequestFromJSON,
    UpdateStudentRequestToJSON,
    UpdateStudentResponseFromJSON,
    UpdateStudentResponseToJSON,
} from '../models/index';

export interface CheckStudentCodeExistsRequest {
    studentCode: string;
}

export interface CreateStudentOperationRequest {
    createStudentRequest: CreateStudentRequest;
}

export interface DeleteStudentRequest {
    id: number;
}

export interface ExportStudentsDataRequest {
    studentSearchRequest?: StudentSearchRequest;
}

export interface GetAllStudentsRequest {
    page?: number;
    pageSize?: number;
}

export interface GetStudentByCodeRequest {
    studentCode: string;
}

export interface GetStudentByIdRequest {
    id: number;
}

export interface GetStudentsByAdvisorRequest {
    advisorCode: string;
    page?: number;
    pageSize?: number;
}

export interface GetStudentsByCampusRequest {
    campusCode: string;
    page?: number;
    pageSize?: number;
}

export interface GetStudentsByFacultyRequest {
    facultyCode: string;
    page?: number;
    pageSize?: number;
}

export interface GetStudentsByMajorRequest {
    majorCode: string;
    page?: number;
    pageSize?: number;
}

export interface GetStudentsByStatusRequest {
    studentStatusId: number;
    page?: number;
    pageSize?: number;
}

export interface ImportStudentsDataOperationRequest {
    importStudentsDataRequest: ImportStudentsDataRequest;
}

export interface SearchStudentsRequest {
    studentSearchRequest: StudentSearchRequest;
    page?: number;
    pageSize?: number;
}

export interface UpdateStudentOperationRequest {
    id: number;
    updateStudentRequest: UpdateStudentRequest;
}

/**
 * STUDENTMANAGEMENTApi - interface
 * 
 * @export
 * @interface STUDENTMANAGEMENTApiInterface
 */
export interface STUDENTMANAGEMENTApiInterface {
    /**
     * ตรวจสอบ studentCode ซ้ำ
     * @param {string} studentCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    checkStudentCodeExistsRaw(requestParameters: CheckStudentCodeExistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckUsernameExists200Response>>;

    /**
     * ตรวจสอบ studentCode ซ้ำ
     */
    checkStudentCodeExists(requestParameters: CheckStudentCodeExistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckUsernameExists200Response>;

    /**
     * สร้าง student ใหม่
     * @param {CreateStudentRequest} createStudentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    createStudentRaw(requestParameters: CreateStudentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateStudentResponse>>;

    /**
     * สร้าง student ใหม่
     */
    createStudent(requestParameters: CreateStudentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateStudentResponse>;

    /**
     * ลบ student
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    deleteStudentRaw(requestParameters: DeleteStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteUser200Response>>;

    /**
     * ลบ student
     */
    deleteStudent(requestParameters: DeleteStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteUser200Response>;

    /**
     * Export student data เป็น CSV
     * @param {StudentSearchRequest} [studentSearchRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    exportStudentsDataRaw(requestParameters: ExportStudentsDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExportStudentsData200Response>>;

    /**
     * Export student data เป็น CSV
     */
    exportStudentsData(requestParameters: ExportStudentsDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExportStudentsData200Response>;

    /**
     * ดู student ทั้งหมด (พร้อม pagination)
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    getAllStudentsRaw(requestParameters: GetAllStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>>;

    /**
     * ดู student ทั้งหมด (พร้อม pagination)
     */
    getAllStudents(requestParameters: GetAllStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse>;

    /**
     * ดู student ตาม studentCode
     * @param {string} studentCode 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    getStudentByCodeRaw(requestParameters: GetStudentByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentResponse>>;

    /**
     * ดู student ตาม studentCode
     */
    getStudentByCode(requestParameters: GetStudentByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentResponse>;

    /**
     * ดู student ตาม id
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    getStudentByIdRaw(requestParameters: GetStudentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentResponse>>;

    /**
     * ดู student ตาม id
     */
    getStudentById(requestParameters: GetStudentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentResponse>;

    /**
     * สถิติของ student
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    getStudentStatisticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentStatisticsResponse>>;

    /**
     * สถิติของ student
     */
    getStudentStatistics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentStatisticsResponse>;

    /**
     * ดู student ตาม advisor
     * @param {string} advisorCode 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    getStudentsByAdvisorRaw(requestParameters: GetStudentsByAdvisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>>;

    /**
     * ดู student ตาม advisor
     */
    getStudentsByAdvisor(requestParameters: GetStudentsByAdvisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse>;

    /**
     * ดู student ตาม campus
     * @param {string} campusCode 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    getStudentsByCampusRaw(requestParameters: GetStudentsByCampusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>>;

    /**
     * ดู student ตาม campus
     */
    getStudentsByCampus(requestParameters: GetStudentsByCampusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse>;

    /**
     * ดู student ตาม faculty
     * @param {string} facultyCode 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    getStudentsByFacultyRaw(requestParameters: GetStudentsByFacultyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>>;

    /**
     * ดู student ตาม faculty
     */
    getStudentsByFaculty(requestParameters: GetStudentsByFacultyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse>;

    /**
     * ดู student ตาม major
     * @param {string} majorCode 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    getStudentsByMajorRaw(requestParameters: GetStudentsByMajorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>>;

    /**
     * ดู student ตาม major
     */
    getStudentsByMajor(requestParameters: GetStudentsByMajorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse>;

    /**
     * ดู student ตาม status
     * @param {number} studentStatusId 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    getStudentsByStatusRaw(requestParameters: GetStudentsByStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>>;

    /**
     * ดู student ตาม status
     */
    getStudentsByStatus(requestParameters: GetStudentsByStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse>;

    /**
     * Import student data จาก CSV
     * @param {ImportStudentsDataRequest} importStudentsDataRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    importStudentsDataRaw(requestParameters: ImportStudentsDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportStudentsData200Response>>;

    /**
     * Import student data จาก CSV
     */
    importStudentsData(requestParameters: ImportStudentsDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportStudentsData200Response>;

    /**
     * ค้นหา student ด้วยเงื่อนไขต่างๆ
     * @param {StudentSearchRequest} studentSearchRequest 
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    searchStudentsRaw(requestParameters: SearchStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>>;

    /**
     * ค้นหา student ด้วยเงื่อนไขต่างๆ
     */
    searchStudents(requestParameters: SearchStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse>;

    /**
     * อัปเดต student
     * @param {number} id 
     * @param {UpdateStudentRequest} updateStudentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof STUDENTMANAGEMENTApiInterface
     */
    updateStudentRaw(requestParameters: UpdateStudentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateStudentResponse>>;

    /**
     * อัปเดต student
     */
    updateStudent(requestParameters: UpdateStudentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateStudentResponse>;

}

/**
 * 
 */
export class STUDENTMANAGEMENTApi extends runtime.BaseAPI implements STUDENTMANAGEMENTApiInterface {

    /**
     * ตรวจสอบ studentCode ซ้ำ
     */
    async checkStudentCodeExistsRaw(requestParameters: CheckStudentCodeExistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CheckUsernameExists200Response>> {
        if (requestParameters['studentCode'] == null) {
            throw new runtime.RequiredError(
                'studentCode',
                'Required parameter "studentCode" was null or undefined when calling checkStudentCodeExists().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/check-code/{studentCode}`;
        urlPath = urlPath.replace(`{${"studentCode"}}`, encodeURIComponent(String(requestParameters['studentCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckUsernameExists200ResponseFromJSON(jsonValue));
    }

    /**
     * ตรวจสอบ studentCode ซ้ำ
     */
    async checkStudentCodeExists(requestParameters: CheckStudentCodeExistsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CheckUsernameExists200Response> {
        const response = await this.checkStudentCodeExistsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * สร้าง student ใหม่
     */
    async createStudentRaw(requestParameters: CreateStudentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateStudentResponse>> {
        if (requestParameters['createStudentRequest'] == null) {
            throw new runtime.RequiredError(
                'createStudentRequest',
                'Required parameter "createStudentRequest" was null or undefined when calling createStudent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/student/create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateStudentRequestToJSON(requestParameters['createStudentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateStudentResponseFromJSON(jsonValue));
    }

    /**
     * สร้าง student ใหม่
     */
    async createStudent(requestParameters: CreateStudentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateStudentResponse> {
        const response = await this.createStudentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ลบ student
     */
    async deleteStudentRaw(requestParameters: DeleteStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DeleteUser200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteStudent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DeleteUser200ResponseFromJSON(jsonValue));
    }

    /**
     * ลบ student
     */
    async deleteStudent(requestParameters: DeleteStudentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DeleteUser200Response> {
        const response = await this.deleteStudentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Export student data เป็น CSV
     */
    async exportStudentsDataRaw(requestParameters: ExportStudentsDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ExportStudentsData200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/student/export`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StudentSearchRequestToJSON(requestParameters['studentSearchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ExportStudentsData200ResponseFromJSON(jsonValue));
    }

    /**
     * Export student data เป็น CSV
     */
    async exportStudentsData(requestParameters: ExportStudentsDataRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ExportStudentsData200Response> {
        const response = await this.exportStudentsDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ดู student ทั้งหมด (พร้อม pagination)
     */
    async getAllStudentsRaw(requestParameters: GetAllStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentSearchResponseFromJSON(jsonValue));
    }

    /**
     * ดู student ทั้งหมด (พร้อม pagination)
     */
    async getAllStudents(requestParameters: GetAllStudentsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse> {
        const response = await this.getAllStudentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ดู student ตาม studentCode
     */
    async getStudentByCodeRaw(requestParameters: GetStudentByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentResponse>> {
        if (requestParameters['studentCode'] == null) {
            throw new runtime.RequiredError(
                'studentCode',
                'Required parameter "studentCode" was null or undefined when calling getStudentByCode().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/code/{studentCode}`;
        urlPath = urlPath.replace(`{${"studentCode"}}`, encodeURIComponent(String(requestParameters['studentCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentResponseFromJSON(jsonValue));
    }

    /**
     * ดู student ตาม studentCode
     */
    async getStudentByCode(requestParameters: GetStudentByCodeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentResponse> {
        const response = await this.getStudentByCodeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ดู student ตาม id
     */
    async getStudentByIdRaw(requestParameters: GetStudentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getStudentById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentResponseFromJSON(jsonValue));
    }

    /**
     * ดู student ตาม id
     */
    async getStudentById(requestParameters: GetStudentByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentResponse> {
        const response = await this.getStudentByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * สถิติของ student
     */
    async getStudentStatisticsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentStatisticsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/statistics`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentStatisticsResponseFromJSON(jsonValue));
    }

    /**
     * สถิติของ student
     */
    async getStudentStatistics(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentStatisticsResponse> {
        const response = await this.getStudentStatisticsRaw(initOverrides);
        return await response.value();
    }

    /**
     * ดู student ตาม advisor
     */
    async getStudentsByAdvisorRaw(requestParameters: GetStudentsByAdvisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>> {
        if (requestParameters['advisorCode'] == null) {
            throw new runtime.RequiredError(
                'advisorCode',
                'Required parameter "advisorCode" was null or undefined when calling getStudentsByAdvisor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/advisor/{advisorCode}`;
        urlPath = urlPath.replace(`{${"advisorCode"}}`, encodeURIComponent(String(requestParameters['advisorCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentSearchResponseFromJSON(jsonValue));
    }

    /**
     * ดู student ตาม advisor
     */
    async getStudentsByAdvisor(requestParameters: GetStudentsByAdvisorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse> {
        const response = await this.getStudentsByAdvisorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ดู student ตาม campus
     */
    async getStudentsByCampusRaw(requestParameters: GetStudentsByCampusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>> {
        if (requestParameters['campusCode'] == null) {
            throw new runtime.RequiredError(
                'campusCode',
                'Required parameter "campusCode" was null or undefined when calling getStudentsByCampus().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/campus/{campusCode}`;
        urlPath = urlPath.replace(`{${"campusCode"}}`, encodeURIComponent(String(requestParameters['campusCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentSearchResponseFromJSON(jsonValue));
    }

    /**
     * ดู student ตาม campus
     */
    async getStudentsByCampus(requestParameters: GetStudentsByCampusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse> {
        const response = await this.getStudentsByCampusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ดู student ตาม faculty
     */
    async getStudentsByFacultyRaw(requestParameters: GetStudentsByFacultyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>> {
        if (requestParameters['facultyCode'] == null) {
            throw new runtime.RequiredError(
                'facultyCode',
                'Required parameter "facultyCode" was null or undefined when calling getStudentsByFaculty().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/faculty/{facultyCode}`;
        urlPath = urlPath.replace(`{${"facultyCode"}}`, encodeURIComponent(String(requestParameters['facultyCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentSearchResponseFromJSON(jsonValue));
    }

    /**
     * ดู student ตาม faculty
     */
    async getStudentsByFaculty(requestParameters: GetStudentsByFacultyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse> {
        const response = await this.getStudentsByFacultyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ดู student ตาม major
     */
    async getStudentsByMajorRaw(requestParameters: GetStudentsByMajorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>> {
        if (requestParameters['majorCode'] == null) {
            throw new runtime.RequiredError(
                'majorCode',
                'Required parameter "majorCode" was null or undefined when calling getStudentsByMajor().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/major/{majorCode}`;
        urlPath = urlPath.replace(`{${"majorCode"}}`, encodeURIComponent(String(requestParameters['majorCode'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentSearchResponseFromJSON(jsonValue));
    }

    /**
     * ดู student ตาม major
     */
    async getStudentsByMajor(requestParameters: GetStudentsByMajorRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse> {
        const response = await this.getStudentsByMajorRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ดู student ตาม status
     */
    async getStudentsByStatusRaw(requestParameters: GetStudentsByStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>> {
        if (requestParameters['studentStatusId'] == null) {
            throw new runtime.RequiredError(
                'studentStatusId',
                'Required parameter "studentStatusId" was null or undefined when calling getStudentsByStatus().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/student/status/{studentStatusId}`;
        urlPath = urlPath.replace(`{${"studentStatusId"}}`, encodeURIComponent(String(requestParameters['studentStatusId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentSearchResponseFromJSON(jsonValue));
    }

    /**
     * ดู student ตาม status
     */
    async getStudentsByStatus(requestParameters: GetStudentsByStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse> {
        const response = await this.getStudentsByStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Import student data จาก CSV
     */
    async importStudentsDataRaw(requestParameters: ImportStudentsDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportStudentsData200Response>> {
        if (requestParameters['importStudentsDataRequest'] == null) {
            throw new runtime.RequiredError(
                'importStudentsDataRequest',
                'Required parameter "importStudentsDataRequest" was null or undefined when calling importStudentsData().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/student/import`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImportStudentsDataRequestToJSON(requestParameters['importStudentsDataRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportStudentsData200ResponseFromJSON(jsonValue));
    }

    /**
     * Import student data จาก CSV
     */
    async importStudentsData(requestParameters: ImportStudentsDataOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportStudentsData200Response> {
        const response = await this.importStudentsDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ค้นหา student ด้วยเงื่อนไขต่างๆ
     */
    async searchStudentsRaw(requestParameters: SearchStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StudentSearchResponse>> {
        if (requestParameters['studentSearchRequest'] == null) {
            throw new runtime.RequiredError(
                'studentSearchRequest',
                'Required parameter "studentSearchRequest" was null or undefined when calling searchStudents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['pageSize'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/student/search`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: StudentSearchRequestToJSON(requestParameters['studentSearchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StudentSearchResponseFromJSON(jsonValue));
    }

    /**
     * ค้นหา student ด้วยเงื่อนไขต่างๆ
     */
    async searchStudents(requestParameters: SearchStudentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StudentSearchResponse> {
        const response = await this.searchStudentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * อัปเดต student
     */
    async updateStudentRaw(requestParameters: UpdateStudentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UpdateStudentResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateStudent().'
            );
        }

        if (requestParameters['updateStudentRequest'] == null) {
            throw new runtime.RequiredError(
                'updateStudentRequest',
                'Required parameter "updateStudentRequest" was null or undefined when calling updateStudent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/student/update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateStudentRequestToJSON(requestParameters['updateStudentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UpdateStudentResponseFromJSON(jsonValue));
    }

    /**
     * อัปเดต student
     */
    async updateStudent(requestParameters: UpdateStudentOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UpdateStudentResponse> {
        const response = await this.updateStudentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
